import React,{useState,useEffect} from 'react';
import {ChevronRight,RotateCcw,ArrowUpRight,ArrowRight,Check,SlidersHorizontal} from 'lucide-react';
import {quantize} from './graph-math.js';
import {Range,Metric} from './ui.jsx';

export function MindMap({topic,language}){
  const [selected,setSelected]=useState(null);const tx=(zh,en)=>language==='en'?en:zh;
  useEffect(()=>setSelected(null),[topic.id]);
  return <div className="chapter-mindmap" style={{'--topic-color':topic.color}}><div className="map-root"><span>{topic.name.split('：')[0].split(':')[0]}</span></div><div className="mindmap-tree"><svg className="map-wires" viewBox="0 0 1000 70" preserveAspectRatio="none" aria-hidden="true"><path d="M500 0V20Q500 34 480 34H187Q167 34 167 54V70 M500 0V70 M500 0V20Q500 34 520 34H813Q833 34 833 54V70"/><circle r="3"><animateMotion dur="4s" repeatCount="indefinite" path="M500 0V20Q500 34 480 34H187Q167 34 167 54V70"/></circle><circle r="3"><animateMotion dur="3s" repeatCount="indefinite" path="M500 0V70"/></circle><circle r="3"><animateMotion dur="4.5s" repeatCount="indefinite" path="M500 0V20Q500 34 520 34H813Q833 34 833 54V70"/></circle></svg><div className="mindmap-branches">{topic.nodes.map((n,i)=><button key={i} className={selected===i?'selected':''} aria-pressed={selected===i} style={{'--branch-color':['#0b91ca','#dd517d','#1a9b73'][i%3]}} onClick={()=>setSelected(selected===i?null:i)}><span className="branch-number">0{i+1}</span><strong>{n.name}</strong><ChevronRight size={15}/></button>)}</div></div>{selected!==null?<div className="map-description" role="status"><span style={{color:topic.color}}>{topic.nodes[selected].name}</span><p>{topic.nodes[selected].detail}</p>{topic.nodes[selected].link&&<a href={`#${topic.nodes[selected].link}`}>{tx('关联知识','Related concept')}<ArrowUpRight size={13}/></a>}</div>:<p className="map-hint">{tx('点击分支，看它在这次计算中做什么。','Select a branch to see its role in the computation.')}</p>}</div>;
}

export function FlowLab({topic,language}){
  const [step,setStep]=useState(0);const tx=(zh,en)=>language==='en'?en:zh;
  const current=topic.process[step];
  return <div className="flow-lab" style={{'--topic-color':topic.color}}><div className="flow-card-track">{topic.process.map((s,i)=><React.Fragment key={i}><button className={`flow-card ${step===i?'selected':''} ${step>i?'visited':''}`} aria-pressed={step===i} onClick={()=>setStep(i)}><span className="flow-number">{i<step?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><strong>{s.name}</strong><span className="flow-payload">{s.output}</span></button>{i<3&&<div className={`flow-arrow ${step>i?'active':''}`}><ArrowRight size={18}/><i/></div>}</React.Fragment>)}</div><div className="flow-inspector"><div><span className="tiny-label">{tx('当前步骤','CURRENT STEP')} {step+1} / 4</span><h3>{current.name}</h3><p>{current.detail}</p></div><div className="flow-io"><div><small>{tx('输入','INPUT')}</small><code>{current.input}</code></div><ChevronRight size={15}/><div><small>{tx('输出','OUTPUT')}</small><code>{current.output}</code></div></div></div><div className="flow-navigation"><button className="v4-primary" disabled={step===3} onClick={()=>setStep(s=>s+1)}>{step===3?tx('这一轮已结束','Cycle complete'):tx('继续一步','Next step')}<ChevronRight size={16}/></button><button className="v4-quiet" onClick={()=>setStep(0)}><RotateCcw size={14}/>{tx('从头看','Restart')}</button><small>{tx('教学流程 · 可点选步骤 · 不调用在线模型','Teaching flow · Select steps · No online model calls')}</small></div>{topic.lab&&<MiniLab kind={topic.lab} language={language}/>}</div>;
}

function MiniLab({kind,language}){
  const tx=(zh,en)=>language==='en'?en:zh;const [amount,setAmount]=useState(kind==='quantization'?4:kind==='embedding'?35:.25);
  if(kind==='quantization'){
    const original=[-.94,-.72,-.4,-.15,.12,.37,.68,.91],r=quantize(original,amount);
    return <div className="mini-lab"><div className="mini-lab-heading"><SlidersHorizontal size={16}/><strong>{tx('动手量化一组数','Quantize actual numbers')}</strong></div><div className="quant-bars">{original.map((x,i)=><div key={i}><div className="quant-bar-pair"><span style={{height:`${(x+1)*45+5}px`}}/><span style={{height:`${(r.approx[i]+1)*45+5}px`}}/></div><code>{x.toFixed(2)}</code><small>{r.approx[i].toFixed(2)}</small></div>)}</div><div className="mini-controls"><Range label={tx('位数','Bits')} value={amount} min={2} max={8} step={1} display={`${amount} bit`} onChange={setAmount}/><Metric label={tx('均方误差','Mean squared error')} value={r.mse.toFixed(6)} note={`${r.levels} ${tx('个离散值','discrete values')}`}/></div><p className="mini-lab-note">{tx('蓝色为原值，玫红为恢复值。[-1,1] 上的均匀量化；柱高加了相同偏移方便比较，不表示数值符号。','Blue: original; pink: reconstructed. Uniform quantization on [-1,1]. Bar heights share an offset for comparison and do not encode sign.')}</p></div>;
  }
  if(kind==='embedding'){
    const a=amount*Math.PI/180,x=235+Math.cos(a)*125,y=175-Math.sin(a)*125;
    return <div className="mini-lab"><div className="mini-lab-heading"><SlidersHorizontal size={16}/><strong>{tx('方向如何改变相似度？','How does direction change similarity?')}</strong></div><div className="embedding-demo"><svg viewBox="0 0 470 350" role="img" aria-label={tx('人工二维向量的夹角与 cosine','Angle and cosine of artificial 2D vectors')}><circle cx="235" cy="175" r="125" fill="none" stroke="currentColor" opacity=".15"/><path d="M70 175H400 M235 25V245" stroke="currentColor" opacity=".18"/><path d="M235 175H360" stroke="#0b91ca" strokeWidth="3"/><path d={`M235 175L${x} ${y}`} stroke="#dd517d" strokeWidth="3"/><circle cx={x} cy={y} r="6" fill="#dd517d"/><text x="364" y="169">A</text><text x={x-7} y={y-13}>B</text></svg></div><div className="mini-controls"><Range label={tx('夹角','Angle')} value={amount} min={0} max={180} step={1} display={`${amount}°`} onChange={setAmount}/><Metric label="Cosine similarity" value={Math.cos(a).toFixed(3)} note={tx('单位向量的点积','Dot product of unit vectors')}/></div><p className="mini-lab-note">{tx('这里只计算人工二维向量，不是实际文本模型输出。','Artificial 2D vectors, not embeddings produced by a text model.')}</p></div>;
  }
  const alpha=Math.exp(-amount*5),signal=Array.from({length:64},(_,i)=>Math.sin(i*.22)*.8),noise=signal.map((_,i)=>Math.sin(i*97.3+4)*1.3),mixed=signal.map((x,i)=>Math.sqrt(alpha)*x+Math.sqrt(1-alpha)*noise[i]);
  const path=values=>values.map((v,i)=>`${i?'L':'M'}${20+i*7} ${90-v*45}`).join(' ');
  return <div className="mini-lab"><div className="mini-lab-heading"><SlidersHorizontal size={16}/><strong>{tx('前向加噪：信号逐渐变淡','Forward noising: the signal fades')}</strong></div><svg className="noise-plot" viewBox="0 0 490 180" role="img" aria-label={tx('原信号与加噪信号','Original and noisy signal')}><path d={path(signal)} stroke="#0b91ca" strokeWidth="2" fill="none" opacity=".5"/><path d={path(mixed)} stroke="#dd517d" strokeWidth="2" fill="none"/></svg><div className="mini-controls"><Range label={tx('加噪进度 t','Noising time t')} value={amount} min={0} max={1} onChange={setAmount}/><Metric label="ᾱ(t)" value={alpha.toFixed(3)} note="ᾱ(t) = exp(−5t)"/></div><p className="mini-lab-note">{tx('xₜ = √ᾱ x₀ + √(1−ᾱ) ε。固定伪噪声用于比较；这不是训练好的生成模型。','xₜ = √ᾱ x₀ + √(1−ᾱ) ε. Fixed pseudo-noise for comparison; this is not a trained generation model.')}</p></div>;
}
