import originals from './originals.json';

const book = (path) => `https://www.rethink.fun/${path}`;
const paper = (title, url, date) => ({ title, url, date });
const chapter = (id, num, name, title, summary, experiment, paragraphs, formula, details, related, source, extra = {}) => ({
  id, num, name, title, summary, experiment, paragraphs, formula, details, related,
  sources: [paper(`RethinkFun · ${name}`, book(source), '原教程')], ...extra,
});

export const lessons = [
  chapter('intro', 1, '初识深度学习', '先看数据，再看模型。', '模型从样本中学习规律。真正需要检验的是：这些规律能否用于没见过的数据。', 'regression',
    ['一条直线也可以是一个模型。它接收一个数字，按斜率和截距给出预测；训练则是用样本调整这两个参数，让预测与实际的差距变小。', '深度学习沿用同一套流程，但把直线换成多层可学习的变换。先从[[regression|线性回归]]出发，再理解[[neural|神经网络]]，会比先记架构名称更扎实。'],
    '\\hat y=wx+b',
    [['学习的对象是什么？', '参数 w 和 b 是从训练数据中调整的；模型结构、训练方法和数据选择则由开发者决定。'], ['如何知道模型学到了规律？', '用与训练集分开的验证集选方案，用保留的测试集估计泛化表现。不能用训练误差代替测试表现。']],
    ['regression', 'classification', 'neural'], 'chapter1/什么是深度学习.html'),
  chapter('vectors', 2, '线性代数', '矩阵，让整个空间一起移动。', '观察基向量怎样变化，就能读懂一个二维线性变换。', 'vectors',
    ['向量可以表示位置，也可以存放多个特征。矩阵作用在向量上，相当于先变换每个基向量，再按原来的坐标组合它们。', '下图的浅色网格是原空间，彩色网格是变换后的空间。调节旋转和拉伸，观察网格、基向量与同一个点一起变化。神经网络中的线性层，也是更高维的矩阵运算。'],
    'A\\begin{bmatrix}x\\\\y\\end{bmatrix}=xA\\begin{bmatrix}1\\\\0\\end{bmatrix}+yA\\begin{bmatrix}0\\\\1\\end{bmatrix}',
    [['为什么只看两个基向量就够了？', '二维向量都能写成两个基向量的线性组合。线性变换保持加法和数乘，所以知道这两个向量的去向，就知道所有向量的去向。'], ['线性层与激活函数怎样配合？', '线性层先改变特征空间，激活函数再加入非线性。只有线性层时，多层相乘仍然只是一个线性变换。']],
    ['neural', 'transformer', 'llama'], 'chapter2/线性变换和矩阵.html'),
  chapter('calculus', 3, '微积分', '导数，是此刻的变化速度。', '让点沿曲线移动，观察它的切线。', 'calculus',
    ['在曲线上取两个相邻的点，用纵向变化除以横向变化，就得到这段的平均斜率。把两点间隔不断缩小，极限就是这个位置的导数。', '训练模型时，我们关心的是损失随参数变化的速度。多个参数的偏导数组成[[optimization|梯度]]，告诉我们朝哪个方向调整，损失会上升得最快。'],
    'f\\prime(x)=\\lim_{h\\to0}\\frac{f(x+h)-f(x)}{h}',
    [['梯度为什么指向上升方向？', '在给定位置，梯度与单位方向向量的点积给出方向导数。沿梯度方向，这个值最大；沿负梯度方向，局部下降最快。'], ['链式法则有什么用？', '复合函数的导数由局部导数相乘得到。神经网络的反向传播就是把这条规则沿计算图系统地应用。']],
    ['optimization', 'pytorch', 'regression'], 'chapter3/导数的定义.html'),
  chapter('probability', 4, '概率与统计', '同一个均值，可以有不同的不确定性。', '调节正态分布的均值与标准差，区分位置与分散程度。', 'probability',
    ['均值描述分布的中心，标准差描述数据偏离中心的典型尺度。标准差越大，曲线越宽、峰越低，但整条曲线下的面积仍然是 1。', '连续分布的纵轴是概率密度，不是“恰好等于某个值”的概率。一个区间的概率要对密度积分。模型输出概率时，也要结合校准和实际数据检验其可信程度。'],
    'p(x)=\\frac{1}{\\sigma\\sqrt{2\\pi}}\\exp\\!\\left(-\\frac{(x-\\mu)^2}{2\\sigma^2}\\right)',
    [['为什么密度可能大于 1？', '密度不是单点概率。一个很窄的分布可以有很高的峰，只要积分为 1，就是合法的概率分布。'], ['期望与样本平均有什么区别？', '期望是分布的性质，样本平均是从有限数据计算的统计量。在适当条件下，样本平均会随样本数增加而接近期望。']],
    ['classification', 'nlp', 'evals'], 'chapter4/随机变量及其分布.html'),
  chapter('regression', 5, '线性回归', '让一条直线，慢慢贴近数据。', '调节斜率与截距，或让梯度下降帮你走几步。', 'regression',
    ['模型给每个样本一个预测值。均方误差把预测与标签之间的差平方后求平均，因此较大的错误会受到更重的惩罚。', '下面每条虚线都是一个残差。点击训练后，程序实际计算损失的梯度并更新参数。数值下降说明拟合改善；能否预测新数据，还要看独立的测试集。'],
    'L(w,b)=\\frac1n\\sum_{i=1}^{n}(wx_i+b-y_i)^2',
    [['一次更新到底算了什么？', '分别计算损失对斜率和截距的偏导数，然后用参数减去学习率乘以对应梯度。这里所有数据与计算都在浏览器中完成。'], ['线性回归只能拟合直线吗？', '模型对参数是线性的，但输入可以包含 x² 等非线性特征。因此线性回归也可以拟合曲线，关键是你提供什么特征。']],
    ['calculus', 'optimization', 'pytorch'], 'chapter5/一元线性回归.html', { code: 'chapter5/LinearRegression.py' }),
  chapter('pytorch', 6, 'PyTorch 与自动求导', '从结果，沿计算图往回走。', '把复合计算拆成小步骤，梯度就能逐段传回输入。', 'autodiff',
    ['自动求导会记录张量运算的依赖关系。前向计算得到结果，反向计算沿图应用链式法则，把每个局部梯度组合成参数的梯度。', '这张图使用简单函数 y = (2x + 1)²。改变 x，观察中间值和最终导数同时更新。它展示的是自动求导原理，网页本身没有运行 Python 或 PyTorch。'],
    '\\frac{dy}{dx}=\\frac{dy}{dz}\\frac{dz}{dx}=2z\\cdot2,\\quad z=2x+1',
    [['backward() 和参数更新是同一件事吗？', '不是。backward() 计算并累积梯度；优化器的 step() 再用这些梯度更新参数。常规训练循环还需要清零梯度，避免无意累积。'], ['为什么计算图要拆开？', '每个算子只需要自己的求导规则。复杂的模型可以由这些局部规则组合，无需手动推导一个巨大的整体公式。']],
    ['calculus', 'neural', 'optimization'], 'chapter6/计算图与自动求梯度.html', { code: 'chapter6/AutoGrad.py' }),
  chapter('classification', 7, '逻辑回归', '一个阈值，改变两种错误。', '模型先给出分数，阈值再把分数变成分类决定。', 'classification',
    ['逻辑回归用 Sigmoid 把线性得分映射到 0 到 1。预测概率超过阈值时判为正类，否则判为负类。阈值不是模型参数，却会直接改变使用模型的结果。', '移动阈值，观察漏报、误报、精确率与召回率。没有一个阈值适合所有任务：筛查通常更在意漏报，自动操作可能更在意误报。要结合错误的实际代价选择。'],
    'p(y=1\\mid x)=\\sigma(w^Tx+b),\\quad\\sigma(z)=\\frac1{1+e^{-z}}',
    [['精确率与召回率分别回答什么？', '精确率问“判成正类的样本有多少真的为正”；召回率问“所有真正的正类中找到了多少”。分母为零时，这些指标没有定义。'], ['概率输出就一定可信吗？', '不一定。校准程度、训练数据与实际输入的差异都会影响概率的可靠性。这里的固定样本分数只用于解释阈值。']],
    ['probability', 'neural', 'evals'], 'chapter7/二分类模型的评价指标.html', { code: 'chapter7/Titanic.py' }),
  chapter('neural', 8, '神经网络', '一个神经网络，\n如何得出答案？', '从输入到输出，沿着每一条连接看一次计算。', 'neural',
    ['每个神经元先对输入做加权求和，加上偏置，再经过激活函数。下一层接收这些结果，继续做同样的计算，最后得到预测。', '试着改变两个输入。连线粗细表示权重的绝对值，蓝色是正权重，橙色是负权重；节点中的数字是当前激活值。隐藏层的这些值来自计算，不能自动解释为某种人类概念。'],
    'h=\\phi(W_1x+b_1),\\quad\\hat y=\\sigma(W_2h+b_2)',
    [['没有激活函数会怎样？', '连续的线性变换仍然可以合并成一个线性变换。加入非线性激活，网络才有能力表示更复杂的关系。你可以在实验中切换为“线性”比较。'], ['权重从哪里来？', '真实模型通常从初始化开始，用数据与反向传播学习权重。这里固定了一组小权重，便于观察前向传播；它没有经过训练，输出也不代表现实任务的概率。'], ['“神经元”与大脑是什么关系？', '这里的神经元是一个数学计算单元。名称受生物神经系统启发，但不能据此推断它具有生物神经元或大脑的完整机制。']],
    ['vectors', 'pytorch', 'transformer'], 'chapter8/从逻辑回归到神经网络.html', { code: 'chapter8/MNIST_pytorch.py', challenge: '保持 x₂ 不变，慢慢提高 x₁。为什么有些隐藏节点变亮，另一些变暗？' }),
  chapter('optimization', 9, '优化神经网络', '步子有多大，决定能否走到谷底。', '同一条损失曲线，换一个学习率会发生什么？', 'optimization',
    ['梯度下降用局部斜率决定更新方向，用学习率控制步长。步长很小会走得慢，太大可能左右震荡，甚至离最小值越来越远。', '动量方法会积累过去的更新方向。它常能帮助穿过缓慢变化的区域，但学习率和动量搭配不当也会带来震荡。下面用一维二次函数观察这些现象。'],
    'v_t=\\beta v_{t-1}+\\nabla L(w_t),\\quad w_{t+1}=w_t-\\eta v_t',
    [['这里的稳定条件是什么？', '对 L(w) = w²、无动量的梯度下降，更新为 w ← (1 − 2η)w。当 0 < η < 1 时收敛；η = 1 时持续等幅震荡，η > 1 时发散。其他函数的条件不同。'], ['训练时还应观察什么？', '同时看训练损失、验证损失和梯度状态。训练损失下降而验证表现变差，可能出现过拟合。正则化和数据质量同样重要。']],
    ['calculus', 'regression', 'evals'], 'chapter9/动量梯度下降.html'),
  chapter('convolution', 10, '卷积神经网络', '一个小窗口，扫过整张图。', '移动卷积核，亲手算一次输出像素。', 'convolution',
    ['卷积层在多个位置复用同一组局部权重，提取局部模式。每个位置都把输入窗口与核逐项相乘，再把结果加起来。', '下面用一个 6 × 6 的简化像素图和 3 × 3 的核。点击输出网格的任意格子，左侧就会显示它对应的输入窗口。你可以切换平滑核与边缘核，观察结果的差别。'],
    'Y_{i,j}=\\sum_{u=0}^{2}\\sum_{v=0}^{2}K_{u,v}X_{i+u,j+v}',
    [['这里为何是 4 × 4 输出？', '输入为 6 × 6，核为 3 × 3，步幅为 1、没有填充，所以每个维度的输出大小为 6 − 3 + 1 = 4。'], ['这与数学卷积有什么不同？', '深度学习库通常实现不翻转核的互相关，习惯上仍称为卷积。这里也采用互相关约定。'], ['卷积核需要人为设计吗？', '传统图像处理中常用手工核，神经网络通常从数据中学习核。实验使用已知核，是为了让每次乘加可检查。']],
    ['architectures', 'vectors', 'neural'], 'chapter10/卷积操作.html', { code: 'chapter10/CatVSDog.py' }),
  chapter('architectures', 11, '经典卷积网络', '保留输入，再学习一个改变量。', '残差连接为信息和梯度提供一条直接通路。', 'residual',
    ['残差块不要求每个模块直接重建完整输出，而是学习相对于输入的变化，再把输入加回去。这个加法让恒等映射更容易表示。', '实验用 y = x + F(x) 展示跳跃连接。打开或关闭这条连接，比较输出与导数。真实 ResNet 的 F 包含多个卷积等算子，而这里用简单函数展示结构。'],
    'y=x+F(x),\\quad\\frac{dy}{dx}=1+\\frac{dF(x)}{dx}',
    [['残差连接保证梯度不会消失吗？', '不保证。它提供直接的加法路径，改善深层网络优化，但最终仍取决于具体结构、参数和训练条件。'], ['输入与输出尺寸不同怎么办？', '相加要求形状兼容。通道数或空间尺寸变化时，可以通过投影等操作调整跳跃路径。']],
    ['convolution', 'neural', 'transformer'], 'chapter11/ResNet原理.html', { code: 'chapter11/ResNet.py' }),
  chapter('nlp', 12, '自然语言处理', '下一个词，并非只有一个可能。', '温度改变候选分布，采样从分布中做一次选择。', 'sampling',
    ['语言模型先把文本分成 token，再预测下一个 token 的分数。Softmax 将分数变成分布；采样策略决定从哪些候选中、以什么概率选取。', '温度小于 1 通常让分布更集中，大于 1 让它更平缓。Top-p 则保留累计概率达到阈值的一组最可能候选，再重新归一化。实验使用人工设置的候选得分。'],
    'p_i=\\frac{\\exp(z_i/T)}{\\sum_j\\exp(z_j/T)}',
    [['token 等于一个汉字或一个单词吗？', '不一定。分词器可能把词拆成多个片段，也可能把多个字符合为一个 token。这里的候选文字仅用于展示采样概率。'], ['提高温度就一定更有创意吗？', '它增加低分候选被采样的机会，也可能增加无关或错误输出。温度是生成分布的控制参数，不是创造力或正确性的直接指标。']],
    ['probability', 'pretraining', 'transformer'], 'chapter12/语言模型采样.html'),
  chapter('rnn', 13, '循环神经网络', '读完一个输入，更新一次状态。', '一个共享的状态，把序列中的前后联系起来。', 'sequence',
    ['RNN 逐个处理序列元素。每一步把当前输入与上一步的隐藏状态结合，得到新状态；同一组参数在所有时间步复用。', '逐步推进下方序列，观察隐藏状态如何变化。早期信息要经过多次更新才能影响后来的输出，因此长距离依赖可能更难学习。LSTM 与 GRU 用门控结构改善信息流。'],
    'h_t=\\tanh(W_xx_t+W_hh_{t-1}+b)',
    [['顺序处理有什么影响？', '计算后一步状态需要前一步状态，所以时间维度不能像训练时的自注意力那样同时计算。序列越长，这种依赖越明显。'], ['门控究竟控制什么？', '门通常是 0 到 1 的数值，用来控制保留、写入或读取多少信息。它是一组可学习的数学运算，不是人工指定的记忆内容。']],
    ['translation', 'transformer', 'pytorch'], 'chapter13/RNN.html'),
  chapter('translation', 14, '序列到序列翻译', '生成不同的词，读取不同的上下文。', '点击目标词，观察一组示例对齐权重。', 'translation',
    ['编码器把输入序列变成表示，解码器逐步生成目标序列。注意力让解码器在不同时间步，对输入序列进行不同的加权读取。', '下方是人工构造的中英对齐示例，帮助理解交叉注意力。权重不是翻译模型的真实输出，也不能直接当作模型做出决定的完整解释。'],
    'c_t=\\sum_{s=1}^{n}\\alpha_{t,s}h_s,\\quad\\sum_s\\alpha_{t,s}=1',
    [['训练与生成有什么不同？', '训练时常提供目标序列的前一个真实 token 来预测下一个；生成时则把自己的输出作为下一步输入。评估需要覆盖实际生成流程。'], ['BLEU 能说明全部翻译质量吗？', 'BLEU 衡量与参考译文的 n-gram 重合等特征。它有用，但不能完整覆盖语义、自然程度或所有正确译法。']],
    ['rnn', 'transformer', 'evals'], 'chapter14/模型定义.html', { code: 'chapter14/translator.py' }),
  chapter('transformer', 15, 'Transformer', '一个 token，如何读取其他 token？', '从 Query 与 Key 的匹配，到 Value 的加权组合。', 'attention',
    ['自注意力为每个位置计算 Query、Key 和 Value。Query 与所有 Key 的点积决定匹配分数，缩放后经 Softmax 得到权重，再按这些权重组合 Value。', '下方用二维的人工向量演示一次真实计算。选择一个查询 token，观察每个点积分数和归一化权重；开启因果遮罩后，它只能读取自己与之前的位置。'],
    '\\mathrm{Attention}(Q,K,V)=\\mathrm{softmax}\\!\\left(\\frac{QK^T}{\\sqrt{d_k}}+M\\right)V',
    [['Q、K、V 从哪里来？', '通常由当前输入表示分别乘以三个可学习投影矩阵得到。这里直接给出小向量，省略了投影，以便检查核心计算。'], ['多头注意力是什么？', '多个头使用不同的投影与较小的表示维度，分别计算注意力，再拼接并投影。不能预先保证每个头固定代表语法、材质或其他人类概念。'], ['注意力能完全解释模型吗？', '不能。注意力权重仅是一个中间计算量，输出还受 Value、投影、残差和其他层影响。可视化有助理解运算，但不等于完整的因果解释。']],
    ['vectors', 'pretraining', 'llama'], 'chapter15/注意力机制.html', { code: 'chapter15/transformer.py', sources: [paper('RethinkFun · 注意力机制', book('chapter15/注意力机制.html'), '原教程'), paper('Attention Is All You Need', 'https://arxiv.org/abs/1706.03762', '2017')] }),
  chapter('pretraining', 16, 'BERT 与 GPT', '能看到哪些位置，改变学习任务。', '用遮罩比较双向编码与自回归生成。', 'mask',
    ['BERT 的典型预训练任务包括预测被遮盖的 token，表示可以利用左右上下文。GPT 的自回归任务则用前文预测下一个 token，因果遮罩阻止读取未来位置。', '下方矩阵的行是查询位置，列是可读取的位置。切换模式，观察可见区域。这里只演示注意力可见性：BERT 的掩码语言建模还涉及输入替换与预测目标的选择。'],
    'p(x_1,\\ldots,x_n)=\\prod_{t=1}^{n}p(x_t\\mid x_{<t})',
    [['为什么 GPT 训练时仍能并行？', '训练时完整目标序列已知，配合因果遮罩可同时计算多个位置的预测。推理时未来 token 尚未知，所以通常逐个生成。'], ['预训练结束就能直接做聊天助手吗？', '基础模型学习的是文本分布。助手行为通常还需要后续的指令微调与偏好或强化学习等阶段，具体流程依模型而异。']],
    ['transformer', 'nlp', 'reasoning'], 'chapter16/BERT.html'),
  chapter('llama', 17, 'Llama 与位置编码', '同一个向量，在不同位置旋转。', 'RoPE 把位置信息注入 Query 与 Key。', 'rope',
    ['自注意力本身需要额外的位置机制来区分顺序。旋转位置编码在二维分量对上施加随位置变化的旋转，让点积与相对位置相关。', '调节两个位置，观察旋转后的向量和点积。在这一个二维分量对中，同时平移两个位置不会改变点积。真实模型会在多个分量对上使用不同的旋转频率。'],
    '(R_mq)^T(R_nk)=q^TR_{n-m}k',
    [['为什么旋转能保存某些性质？', '二维旋转矩阵是正交矩阵，因此保存向量长度。两个位置的旋转在点积中合并成相对旋转。'], ['这是否意味着可以无限延长上下文？', '不能。模型训练分布、旋转频率与扩展方法都会影响长上下文表现。公式中的相对位置性质并不是无限泛化的保证。']],
    ['vectors', 'transformer', 'inference'], 'chapter17/旋转位置编码.html', { sources: [paper('RethinkFun · 旋转位置编码', book('chapter17/旋转位置编码.html'), '原教程'), paper('RoFormer: Enhanced Transformer with Rotary Position Embedding', 'https://arxiv.org/abs/2104.09864', '2021')] }),
  chapter('deepseek', 18, 'DeepSeek 与 MoE', '每次计算，只选部分专家。', '路由器决定一个 token 经过哪些前馈网络。', 'moe',
    ['混合专家模型包含多个专家子网络，路由器根据输入选择其中一部分。总参数量可以很大，但每个 token 的专家计算只激活部分参数。', '调节下方的路由得分和 Top-k，观察选择与重新归一化后的权重。这里展示的是简化稀疏路由，真实 DeepSeek 架构还包含共享专家、负载均衡等设计。'],
    'y=\\sum_{i\\in\\mathrm{TopK}(g(x))}\\tilde g_i(x)E_i(x)',
    [['“激活参数少”是否等于内存占用少？', '不等于。未被本次选中的专家权重通常也要存放，可能涉及设备间通信。计算量、存储量和实际延迟需要分别分析。'], ['专家是否有固定的人类专业分工？', '专家的行为由训练决定，不能仅凭路由结构就假定它们分别对应数学、写作或某种职业。']],
    ['neural', 'transformer', 'reasoning'], 'chapter18/MOE.html', { sources: [paper('RethinkFun · MOE', book('chapter18/MOE.html'), '原教程'), paper('DeepSeek-V3 Technical Report', 'https://arxiv.org/abs/2412.19437', '2024')] }),
  {
    id: 'rag', num: 'A1', name: '检索增强生成', title: '先找到证据，再组织回答。', summary: 'RAG 给模型补充可查阅的外部资料。', experiment: 'retrieval', supplement: true,
    paragraphs: ['RAG 通常先用问题检索相关片段，再把这些片段与问题一起交给生成模型。它补充的是当前输入中的证据，不会因此改写模型的权重。', '下方提供一个小型本地资料库。选择问题或输入关键词，可以看到检索排序与命中的片段。它实际运行透明的关键词检索，没有接入生成模型；最终展示的是选中的原文证据。'],
    formula: '\\text{query}\\to\\text{retrieve}\\to\\text{context}\\to\\text{generate}',
    details: [['向量检索与关键词检索有什么区别？', '向量检索用嵌入表示和相似度寻找语义相关片段；关键词检索依据词项等信号匹配。实际系统经常混合两者，再进行重排。'], ['RAG 能消除幻觉吗？', '不能保证。检索可能遗漏、片段可能过期，模型也可能误读证据。应分别检验检索召回、答案与证据的一致性，以及无证据时的行为。']],
    related: ['transformer', 'agents', 'evals'], sources: [paper('Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks', 'https://arxiv.org/abs/2005.11401', '2020')],
  },
  {
    id: 'agents', num: 'A2', name: 'Agent 与工作流', title: '一次工具调用，怎样形成一个循环？', summary: '读取结果、选择下一步、调用工具，再检查结果。', experiment: 'workflow', supplement: true,
    paragraphs: ['固定工作流由程序预先规定路径；Agent 则让模型根据当前状态选择下一步行动与工具。两者都需要执行工具、回传结果并判断何时停止。', '这里用“查找课程资料”的脚本示例展开这个循环。点击节点可以查看输入、输出和执行条件，逐步推进则展示数据如何流动。它是可检查的教学模拟，没有在后台启动真实 Agent。'],
    formula: 's_t\\to\\text{choose tool}\\to\\text{observation}\\to s_{t+1}',
    details: [['模型与工具分别做什么？', '模型产生结构化调用请求，应用程序校验参数并执行工具，再把结果写回上下文。模型说“完成”并不代表外部状态真的改变。'], ['2025：上下文管理', '将可用上下文视为有限资源。保留与当前决策相关的信息，压缩旧记录，必要时从外部笔记或资料中重新读取。具体压缩策略要用任务表现验证。'], ['2026：评估整个执行过程', '评估对象应包括模型、工具、运行环境与最终状态。对同一任务做多次试验，检查完成率、错误操作和资源使用，而不只看最后一句回答。']],
    related: ['rag', 'evals', 'inference'], sources: [paper('Building effective agents · Anthropic', 'https://www.anthropic.com/engineering/building-effective-agents', '2024-12-19'), paper('Effective context engineering for AI agents · Anthropic', 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', '2025-09-29'), paper('Demystifying evals for AI agents · Anthropic', 'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents', '2026-01-09')],
  },
  {
    id: 'inference', num: 'A3', name: '推理与 KV Cache', title: '生成下一个 token，哪些结果可以复用？', summary: 'KV Cache 缓存历史 Key 与 Value，减少重复计算。', experiment: 'cache', supplement: true,
    paragraphs: ['自回归生成时，历史 token 的 Key 与 Value 可以保留在缓存中。每来一个新 token，只需要计算它的新表示，并读取已缓存的历史信息。', '缓存并不免费：序列长度、批量大小、层数、KV 头数与精度都会影响占用。下面计算一个简化的 KV Cache 内存估计，帮助区分模型权重与运行时状态。'],
    formula: 'M_{KV}\\approx2\\,B\\,L\\,S\\,H_{KV}\\,d_h\\,b',
    details: [['这个估计包含哪些东西？', '2 对应 Key 与 Value；B 是批量大小，L 是层数，S 是缓存序列长度，H_KV 是 KV 头数，d_h 是每头维度，b 是每元素字节数。这里不包含权重、临时激活、分配器开销或其他缓存。'], ['GQA 为什么能减少缓存？', '多个查询头共享较少的 KV 头，降低 H_KV。具体模型配置不同，不能只看查询头数量来估计缓存。'], ['量化有什么代价？', '较低精度可以减少存储，但效果取决于量化格式、校准与计算支持。这里的字节数只是理想存储估计，不能代替实际测量。']],
    related: ['pretraining', 'llama', 'lora'], sources: [paper('Hugging Face · Caching', 'https://huggingface.co/docs/transformers/en/cache_explanation', '文档，核对于 2026-10-03')],
  },
  {
    id: 'lora', num: 'A4', name: 'LoRA 微调', title: '冻结大矩阵，只训练一个小更新。', summary: '用低秩矩阵分解减少需要训练的参数。', experiment: 'lowrank', supplement: true,
    paragraphs: ['LoRA 将权重更新写成两个较小矩阵的乘积。原权重保持冻结，训练只调整新增矩阵；较小的秩减少可训练参数，但也限制了更新的表达空间。', '下方改变矩阵维度与秩，计算一个线性层的完整参数量与 LoRA 参数量。比例仅针对这一个权重矩阵，不等于整模型训练显存比例或速度提升比例。'],
    formula: 'W\\prime=W+\\frac{\\alpha}{r}BA,\\quad A\\in\\mathbb R^{r\\times d_{in}},\\quad B\\in\\mathbb R^{d_{out}\\times r}',
    details: [['微调与 RAG 应该怎么选？', '想补充经常更新、需要可引用的事实，可以先检验检索方案；想改变行为模式或任务表现，可以考虑微调。两者可以组合，应以真实任务评估决定。'], ['参数少就一定不会过拟合吗？', '不保证。数据规模与质量、训练轮次、秩和目标层选择都会影响结果。仍应保留独立验证数据。']],
    related: ['vectors', 'rag', 'evals'], sources: [paper('LoRA: Low-Rank Adaptation of Large Language Models', 'https://arxiv.org/abs/2106.09685', '2021'), paper('Hugging Face PEFT · LoRA', 'https://huggingface.co/docs/peft/main/en/conceptual_guides/lora', '文档，核对于 2026-10-03')],
  },
  {
    id: 'reasoning', num: 'A5', name: '推理训练', title: '奖励信号，如何推动策略变化？', summary: '以 DeepSeek-R1 为例，区分训练阶段与推理时的计算。', experiment: 'reward', supplement: true,
    paragraphs: ['强化学习根据奖励调整生成策略。在可以验证答案的任务上，奖励可以来自结果是否正确或输出是否符合格式等信号，但奖励设计会影响模型学到什么。', 'DeepSeek-R1 论文区分了无需先做监督微调的 R1-Zero 实验，与包含冷启动数据及多阶段训练的 R1。下方只演示两个候选动作的简化策略梯度更新，不复现 GRPO 或完整训练。'],
    formula: '\\nabla_\\theta J(\\theta)=\\mathbb E\\big[R(a)\\nabla_\\theta\\log\\pi_\\theta(a)\\big]',
    details: [['更长的推理是否总是更好？', '不一定。推理时增加计算可能帮助某些任务，也会增加延迟和资源消耗。需要按任务与预算测量，不能用文本长度代替正确性。'], ['解释文本等于模型的内部机制吗？', '模型给出的解释是生成文本。它可以帮助交流和检查，但不能自动视为完整、可靠的内部因果记录。']],
    related: ['probability', 'deepseek', 'evals'], sources: [paper('DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning', 'https://arxiv.org/abs/2501.12948', '2025-01-22')],
  },
  {
    id: 'evals', num: 'A6', name: '评估与实践', title: '把“感觉更好”，换成可检查的结果。', summary: '同样的任务，多次运行，并检查最终状态。', experiment: 'evals', supplement: true,
    paragraphs: ['评估先定义什么算成功，再选择能验证它的检查方法。简单任务可以用确定性的代码规则，开放任务可以结合人工判断与经过校准的模型评分。', '下方是一组固定的教学试验记录。你可以按任务筛选，比较单次成功率与多次全部成功的比例。数字来自这组示例数据，不代表任何产品或模型的真实性能。'],
    formula: '\\widehat p=\\frac{\\text{成功试验数}}{\\text{总试验数}}',
    details: [['先做哪种评估比较实用？', '先收集少量真实任务，写出明确成功条件与典型失败情况。保留输入、输出、工具调用与最终状态，再用同一组任务比较改动。'], ['不要只检查最后一句话', '例如检索任务要检查证据是否相关，工具任务要检查操作是否实际完成。模型声称“成功”与环境中的真实结果需要分别核对。'], ['报告数字时带上分母', '小样本、试验间相关性和任务分布都会影响结论。附上任务数、重复次数与条件，避免把示例比例当作稳定性能。']],
    related: ['classification', 'agents', 'rag'], sources: [paper('Demystifying evals for AI agents · Anthropic', 'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents', '2026-01-09')],
  },
];

export const groups = [
  { title: '开始', ids: ['intro'] },
  { title: '数学基础', ids: ['vectors', 'calculus', 'probability'] },
  { title: '从数据到模型', ids: ['regression', 'pytorch', 'classification', 'neural', 'optimization'] },
  { title: '视觉与序列', ids: ['convolution', 'architectures', 'nlp', 'rnn', 'translation'] },
  { title: '大语言模型', ids: ['transformer', 'pretraining', 'llama', 'deepseek'] },
  { title: '原教程之后', ids: ['rag', 'agents', 'inference', 'lora', 'reasoning', 'evals'] },
];

export const byId = Object.fromEntries(lessons.map(l => [l.id, l]));
export const chapterByNumber = Object.fromEntries(lessons.filter(l => !l.supplement).map(l => [l.num, l]));
export const originalSections = originals;

export const workflows = [
  { label: '接收问题', type: '输入', input: '“卷积核为什么可以检测边缘？”', output: '{ task: "解释卷积", needsEvidence: true }', condition: '读取问题，确定完成条件：解释计算，并提供课程证据。', detail: '先记录用户目标。这个示例将问题与期望结果写成状态；实际应用还需要处理缺失信息。' },
  { label: '选择工具', type: '决策', input: '问题 + 可用工具说明', output: '{ tool: "search_course", query: "卷积 边缘" }', condition: '当前上下文缺少课程证据，选择只读搜索工具。', detail: '工具定义需要有清楚的名称、参数与返回结构。此处选择来自固定脚本，并非实时模型决策。' },
  { label: '执行检索', type: '工具', input: 'search_course("卷积 边缘")', output: '[{ chapter: 10, topic: "卷积操作", source: "rethink.fun" }]', condition: '先校验参数，再执行工具。空结果或错误应返回给下一步处理。', detail: '执行发生在应用程序中。真实系统应把工具调用、错误和结果记录下来，便于检查与复现。' },
  { label: '读取证据', type: '观察结果', input: '搜索结果与章节片段', output: '局部窗口与卷积核逐项相乘后求和；差分核突出相邻像素的变化。', condition: '检查片段是否与问题有关，缺少证据时继续检索。', detail: '工具结果是数据，不应被当作控制应用的指令。资料来源和时间也需要与回答一起保留。' },
  { label: '检查并回答', type: '输出', input: '原问题 + 已核对的证据', output: '给出解释与章节链接；标明此处使用手工边缘核。', condition: '问题已覆盖，来源可查，停止循环。若证据不够，则返回选择工具。', detail: '停止条件要与真实任务完成相符。这个案例没有修改外部状态；其他工具任务应检查实际操作结果。' },
];

export const retrievalDocs = [
  { title: '梯度下降', text: '梯度是损失对参数的变化方向。学习率决定每次参数更新的步长。太大的学习率可能让损失发散。', terms: ['梯度', '学习率', '损失', '训练', '参数', '下降', 'gradient', 'learning', 'loss', 'optimization'], id: 'optimization' },
  { title: '卷积与边缘', text: '卷积窗口逐项乘加。边缘核用正负权重对比相邻像素；输出大小由核尺寸、步幅与填充决定。', terms: ['卷积', '边缘', '像素', '图像', '卷积核', '窗口', 'cnn', 'convolution', 'edge', 'pixel'], id: 'convolution' },
  { title: '注意力与遮罩', text: 'Query 与 Key 的点积产生注意力分数，Softmax 得到权重，再组合 Value。因果遮罩阻止读取未来位置。', terms: ['注意力', '遮罩', '未来', 'query', 'key', 'value', 'transformer', 'softmax', 'attention', 'mask'], id: 'transformer' },
  { title: '推理时的 KV Cache', text: '缓存历史 Key 与 Value 能减少重复计算。缓存占用随序列长度和 KV 头数增加，与模型权重内存不同。', terms: ['缓存', '显存', '内存', '推理', 'kv', 'cache', '序列', 'key', 'value', 'memory', 'inference'], id: 'inference' },
  { title: '低秩微调', text: 'LoRA 冻结原权重，通过两个小矩阵训练低秩更新。秩与目标层会影响可训练参数量。', terms: ['lora', '微调', '训练', '秩', '参数', '矩阵', '权重', 'rank', 'fine-tuning'], id: 'lora' },
  { title: 'Agent 的工具循环', text: '模型选择工具，应用执行调用并返回观察。循环需要明确停止条件，评估要检查最终状态。', terms: ['agent', '工具', '循环', '工作流', '停止', '评估', '状态', 'tool', 'workflow'], id: 'agents' },
];
