const p=(zh,en)=>({zh,en});
const ref=(title,url,date='文档核对于 2026-10-03')=>({title,url,date});
const paper=(title,id,date)=>ref(title,`https://arxiv.org/abs/${id}`,date);
const source={
  embed:ref('Sentence Transformers · Quickstart','https://sbert.net/docs/quickstart.html'),
  context:ref('Effective context engineering · Anthropic','https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents','2025-09-29'),
  cot:paper('Chain-of-Thought Prompting','2201.11903','2022'),
  faith:paper('Unfaithful Explanations in CoT','2305.04388','2023'),
  dpo:paper('Direct Preference Optimization','2305.18290','2023'),
  r1:paper('DeepSeek-R1','2501.12948','2025'),
  ddpm:paper('Denoising Diffusion Probabilistic Models','2006.11239','2020'),
  ldm:paper('Latent Diffusion Models','2112.10752','2021 / CVPR 2022'),
  clip:paper('Learning Transferable Visual Models · CLIP','2103.00020','2021'),
  mamba:paper('Mamba · Selective State Spaces','2312.00752','2023'),
  flash:paper('FlashAttention','2205.14135','2022'),
  vllm:paper('PagedAttention · vLLM','2309.06180','2023'),
  fsdp:ref('PyTorch · FSDP2','https://docs.pytorch.org/docs/stable/distributed.fsdp.fully_shard.html'),
  cuda:ref('NVIDIA · CUDA Programming Guide','https://docs.nvidia.com/cuda/cuda-programming-guide/index.html'),
  rocm:ref('AMD · ROCm','https://rocm.docs.amd.com/en/latest/'),
  ascend:ref('昇腾 · 开发文档','https://www.hiascend.com/document'),
  gptq:paper('GPTQ · Post-training quantization','2210.17323','2022'),
  awq:paper('AWQ · Activation-aware Weight Quantization','2306.00978','2023'),
  af3:ref('Accurate structure prediction · AlphaFold 3','https://www.nature.com/articles/s41586-024-07487-w','2024'),
  data:ref('Common pitfalls · scikit-learn','https://scikit-learn.org/stable/common_pitfalls.html'),
  cv:ref('Cross-validation · scikit-learn','https://scikit-learn.org/stable/modules/cross_validation.html'),
  rules:ref('Rules of Machine Learning · Google','https://developers.google.com/machine-learning/guides/rules-of-ml'),
  prompt:ref('Prompt engineering · Anthropic','https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview'),
  skill:ref('Agent Skills · Specification','https://agentskills.io/specification'),
  harness:ref('Effective harnesses for long-running agents','https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents','2025-11-26'),
  rsi:paper('Darwin Gödel Machine','2505.22954','2025 · revised 2026-03'),
  tune:ref('Performance tuning · PyTorch','https://docs.pytorch.org/tutorials/recipes/recipes/tuning_guide.html'),
  jax:ref('JAX · Key concepts','https://docs.jax.dev/en/latest/key-concepts.html'),
  megatron:ref('Megatron Core · NVIDIA','https://docs.nvidia.com/megatron-core/developer-guide/latest/index.html'),
};

// Each field is authored in both languages; flow steps are teaching descriptions.
function topic(id,group,name,summary,joke,analogy,boundary,practice,nodes,process,sources,related,lab){return {id,group,name,summary,joke,analogy,boundary,practice,nodes,process,sources,related,lab,extra:true};}
const node=(name,detail,link)=>({name,detail,link});
const step=(name,detail,input,output)=>({name,detail,input,output});

export const fieldGuide=[
  topic('embeddings','representation',p('Embedding：文本的坐标','Embedding: coordinates for text'),p('把输入映射成向量，才有可比较的距离。','Map inputs to vectors so that similarity can be measured.'),p('“懂的都懂”不够用，搜索得知道“懂”在哪个坐标。','“You know what I mean” needs coordinates before a search engine can use it.'),p('像图书馆按主题排书；相近的位置帮助找相似内容。','Like shelving related books close together in a library.'),p('向量相近取决于训练目标与距离指标，不保证事实正确，也不表示模型具有人的理解。','Closeness depends on the training objective and metric. It does not guarantee truth or human understanding.'),p('用自己的查询与资料检查召回；同时观察漏检与错误近邻。','Check retrieval on your own queries, including misses and misleading neighbors.'),[
    node(p('编码','Encode'),p('输入经过模型得到固定维度向量。','An encoder produces a fixed-dimensional vector.'),'vectors'),node(p('相似度','Similarity'),p('Cosine 比较方向，指标要与模型匹配。','Cosine compares direction; the metric must match the model.'),'rag'),node(p('检索','Retrieve'),p('选出候选后，仍要核对原始资料。','Retrieve candidates, then inspect their original evidence.'),'evals')
  ],[step(p('输入','Input'),p('同一任务选择适合的编码模型。','Choose an encoder suited to the task.'),p('问题 + 文档','Query + documents'),p('待编码文本','Text to encode')),step(p('编码','Encode'),p('真实模型向量有许多维度。','Real embeddings have many dimensions.'),p('文本','Text'),p('向量','Vectors')),step(p('比较','Compare'),p('下面用人工二维向量实际计算 cosine。','The lab calculates cosine using artificial 2D vectors.'),p('向量对','Vector pair'),p('相似度','Similarity')),step(p('核对','Verify'),p('相近的候选不一定支持回答。','A close candidate may still fail to support an answer.'),p('候选资料','Candidates'),p('可用证据','Usable evidence'))],[source.embed],['vectors','rag','context'],'embedding'),

  topic('context','representation',p('Context：工作台有多大','Context: a finite workbench'),p('上下文是这次调用可见的信息，不等同于永久记忆。','Context is information visible to a call, not permanent memory.'),p('工位再大，也别把去年的外卖单都摊上去。','A bigger desk still does not need last year’s receipts.'),p('像工作台：留下当前任务会用到的材料，把历史记录放到可查的柜子里。','Keep relevant materials on a workbench; store older records where they can be retrieved.'),p('窗口容量大不代表每条信息都能同样有效地被利用；压缩也可能丢信息。','A large window does not guarantee equal use of every item, and compression can lose information.'),p('记录目标、关键证据与未完成项，测试压缩之后能否正确接着做。','Keep goals, evidence and unfinished work; test whether work resumes correctly after compaction.'),[
    node(p('选择','Select'),p('只放与下一次决策有关的信息。','Include information needed for the next decision.'),'prompting'),node(p('压缩','Compact'),p('总结历史，但保留可追溯原记录。','Summarize history while retaining original records.'),'harness'),node(p('检索','Retrieve'),p('需要时把外部笔记带回上下文。','Retrieve external notes when needed.'),'rag')
  ],[step(p('目标','Goal'),p('先明确这次任务要完成什么。','Define the current task.'),p('任务','Task'),p('完成条件','Success criteria')),step(p('挑材料','Select'),p('筛选相关事实和工具结果。','Select relevant facts and tool results.'),p('历史资料','History'),p('相关片段','Relevant passages')),step(p('整理','Organize'),p('压缩旧记录，保留引用与未完成项。','Compact old records, preserving references and open items.'),p('片段','Passages'),p('工作上下文','Working context')),step(p('检查','Check'),p('实际续做是否成功，比摘要读起来顺更重要。','Check actual continuation, not just a readable summary.'),p('下一次调用','Next call'),p('任务结果','Task outcome'))],[source.context],['rag','harness','inference']),

  topic('cot','representation',p('CoT：步骤不等于读心','CoT: steps are not mind-reading'),p('中间步骤可能帮助解题；写出来的解释不自动等于内部因果。','Intermediate steps can help solve tasks; written explanations are not automatically faithful mechanisms.'),p('“过程写满了”不代表最后一行能拿分。','A page full of working does not make the final answer correct.'),p('像草稿纸：把子问题拆开，方便检查计算与证据。','Like scratch paper: separate subproblems so calculations and evidence can be checked.'),p('模型可生成合理但不忠实的解释；长文本、长思考时间都不是正确率保证。','Models may produce plausible but unfaithful explanations. Length and time do not guarantee accuracy.'),p('要求可核对的结果、关键依据和测试；不要把索要内部思维过程当成评估方法。','Ask for checkable results, supporting evidence and tests; requesting internal thoughts is not an evaluation method.'),[
    node(p('分解任务','Decompose'),p('拆成有明确输入输出的小问题。','Create smaller problems with clear inputs and outputs.'),'prompting'),node(p('检查步骤','Check'),p('独立验证关键计算与引用。','Independently verify calculations and citations.'),'evals'),node(p('验证结论','Verify'),p('最终答案仍要接受事实与测试检验。','The final result still needs factual checks or tests.'),'results')
  ],[step(p('问题','Problem'),p('例：三盒各四支，取走两支。','Example: three boxes of four pens; remove two.'),p('3×4−2','3×4−2'),p('待检查表达式','Expression to check')),step(p('拆分','Split'),p('先算总数，再算剩余量。','Find the total, then the remainder.'),p('3×4','3×4'),p('12','12')),step(p('验算','Check'),p('用独立计算验证 12−2。','Independently check 12−2.'),p('12−2','12−2'),p('10','10')),step(p('结果','Result'),p('这个手写算例展示可核对步骤，不展示模型内部思维。','This authored arithmetic example shows checkable steps, not internal model thoughts.'),p('已核对计算','Checked arithmetic'),p('剩余 10 支','10 pens remain'))],[source.cot,source.faith],['reasoning','prompting','evals']),

  topic('alignment','representation',p('Post-training：改变行为','Post-training: shape behavior'),p('预训练学文本分布，后训练塑造任务行为与偏好。','Pretraining learns a text distribution; post-training shapes task behavior and preferences.'),p('背过菜谱，不代表上岗就能按你的口味出餐。','Knowing recipes is different from serving a customer’s order.'),p('像厨师岗前训练：先看合格示范，再比较哪些结果更符合要求。','Like job training: learn from demonstrations, then compare preferred outcomes.'),p('SFT、DPO、RL 的目标和数据不同；实际训练方案可能组合它们。','SFT, DPO and RL use different objectives and data; practical pipelines may combine them.'),p('先定义任务、示例质量与验证集；别只按一个训练方法的新名字选方案。','Define tasks, demonstration quality and held-out evaluation before choosing a method.'),[
    node(p('SFT','SFT'),p('用输入与目标输出监督训练。','Train on inputs paired with target outputs.'),'lora'),node(p('偏好优化','Preferences'),p('DPO 等方法利用偏好对。','Methods such as DPO use preference pairs.'),'reasoning'),node(p('奖励与评估','Reward & eval'),p('RL 使用奖励；最终行为仍需独立评估。','RL uses reward signals; behavior still needs independent evaluation.'),'evals')
  ],[step(p('基础模型','Base model'),p('它已有预训练能力，但任务行为未必合适。','Pretrained capabilities may not match task behavior.'),p('模型','Model'),p('基线结果','Baseline')),step(p('示范','Examples'),p('SFT 学习合格输入输出对。','SFT learns from suitable input-output pairs.'),p('示例数据','Demonstrations'),p('任务行为','Task behavior')),step(p('偏好 / 奖励','Preference / reward'),p('不同优化方法使用不同信号。','Different methods optimize different signals.'),p('偏好或可验证奖励','Preferences or verifiable rewards'),p('候选策略','Candidate policy')),step(p('独立评估','Evaluate'),p('不要用训练样本替代真实任务验证。','Do not substitute training examples for held-out task evaluation.'),p('候选模型','Candidate model'),p('任务报告','Task report'))],[source.dpo,source.r1],['pretraining','lora','reasoning']),

  topic('diffusion','representation',p('Diffusion：从噪声学会生成','Diffusion: learning to generate'),p('训练模型估计去噪方向，生成时逐步更新样本。','Train a model to estimate denoising directions, then iteratively update samples.'),p('照片糊了可以修，“原图在哪”不能靠许愿。','A blurred photo needs a learned model, not a wish for the original.'),p('像练习从带噪草稿辨认结构；训练时原图与噪声已知。','Practice recognizing structure in noisy drafts; training has known clean data and noise.'),p('生成不是找回某一张已知原图。此实验只展示前向加噪，没训练反向去噪模型。','Generation does not recover a particular known original. This lab only demonstrates forward noising, without a trained denoiser.'),p('分清像素空间与 latent 空间、训练目标、采样步数和条件控制；比较质量与耗时。','Distinguish pixel and latent spaces, training targets, sampling steps and conditioning; compare quality with latency.'),[
    node(p('前向加噪','Add noise'),p('混合已知图形与固定噪声。','Mix a known pattern with fixed noise.'),'probability'),node(p('学习去噪','Learn denoising'),p('训练网络预测噪声或其他目标。','Train a network to predict noise or other targets.'),'neural'),node(p('条件生成','Condition'),p('文本等条件引导采样；latent 方法先压缩表示。','Conditions guide sampling; latent methods use compressed representations.'),'multimodal')
  ],[step(p('训练样本','Examples'),p('训练时可获得干净样本。','Clean examples are available during training.'),p('x₀','x₀'),p('干净数据','Clean data')),step(p('加噪','Noising'),p('下面实际显示信号与固定噪声的混合。','The lab displays actual signal-noise mixing.'),p('x₀ + ε','x₀ + ε'),p('xₜ','xₜ')),step(p('训练','Training'),p('网络用监督目标学习估计，而非知道每次原图。','A network learns an estimator from training targets.'),p('xₜ、t、条件','xₜ, t, condition'),p('估计方向','Estimated direction')),step(p('采样','Sampling'),p('生成依赖训练模型与采样方法；此处不执行模型生成。','Generation needs a trained model and sampler; neither is executed here.'),p('初始噪声','Initial noise'),p('生成样本','Generated sample'))],[source.ddpm,source.ldm],['probability','neural','multimodal'],'diffusion'),

  topic('multimodal','representation',p('Multimodal：不同输入，同一任务','Multimodal: different inputs'),p('把图像、声音或文本表示接入任务，训练决定它们如何关联。','Connect image, audio or text representations to a task; training determines their relationships.'),p('图都看了，标题还张冠李戴？表示得先对齐。','Seeing an image does not help if its caption is mismatched.'),p('像多人协作前统一地图坐标，文字与图像才有可比较的表示。','Like agreeing on map coordinates before comparing observations.'),p('CLIP 的对比表示不等于完整视觉问答；多模态输入仍可能被误读。','CLIP contrastive representations are not a complete visual-question-answering system. Inputs can still be misread.'),p('用图文一致性、细节识别和缺失信息测试模型，保留原始输入与结果。','Test image-text consistency, details and missing information; retain original inputs and outputs.'),[
    node(p('编码输入','Encode'),p('不同模态可以使用不同编码器。','Different modalities may use different encoders.'),'embeddings'),node(p('对齐 / 融合','Align / fuse'),p('训练目标定义表示间的关联。','Training objectives define relationships between representations.'),'alignment'),node(p('检查细节','Check details'),p('能给概括，不保证看清每个数字。','A useful summary does not guarantee every digit was read correctly.'),'results')
  ],[step(p('原始输入','Inputs'),p('图像、声音和文本有不同结构。','Images, audio and text have different structures.'),p('图像 + 问题','Image + question'),p('原始材料','Raw material')),step(p('编码','Encode'),p('编码器提取可供任务使用的表示。','Encoders produce task representations.'),p('材料','Material'),p('特征','Features')),step(p('关联','Connect'),p('通过对比学习或融合训练建立联系。','Contrastive or fusion training establishes relationships.'),p('特征 + 文本','Features + text'),p('任务表示','Task representation')),step(p('验证','Verify'),p('实际核对可观察细节。','Verify observable details.'),p('回答','Answer'),p('正确或错误的记录','Outcome record'))],[source.clip],['embeddings','diffusion','evals']),

  topic('new-architectures','representation',p('新架构：先看计算，再看名字','New architectures: inspect computation'),p('Attention、状态空间与混合结构，是不同的信息处理方式。','Attention, state spaces and hybrid structures process information differently.'),p('换个炫酷名字，不会自动让显存下班。','A new name does not give your memory allocator a day off.'),p('像查资料与做滚动笔记：一种读取历史内容，一种更新可携带的状态。','Like consulting an archive versus updating a running note.'),p('这是结构类比。真实复杂度、能力与速度取决于具体实现、长度与硬件。','This is an architectural analogy. Complexity, capability and speed depend on implementation, length and hardware.'),p('区分改变模型结构的 Mamba 与优化 Attention 计算的 FlashAttention；后者不把 Softmax 换成新架构。','Distinguish Mamba’s model structure from FlashAttention’s optimized attention computation; the latter is not a replacement model architecture.'),[
    node(p('读取历史','Read history'),p('Attention 根据当前查询组合历史表示。','Attention combines past representations using a query.'),'transformer'),node(p('更新状态','Update state'),p('选择性状态空间利用输入相关机制更新状态。','Selective state spaces use input-dependent state updates.'),'rnn'),node(p('优化 IO','Optimize IO'),p('FlashAttention 减少存储读写，保持注意力计算目标。','FlashAttention reduces memory traffic while preserving exact attention.'),'infra')
  ],[step(p('任务约束','Constraints'),p('先确定长度、吞吐、内存与质量要求。','Define length, throughput, memory and quality requirements.'),p('任务','Task'),p('约束','Constraints')),step(p('结构','Structure'),p('比较 Attention、状态空间或混合设计。','Compare attention, state-space or hybrid designs.'),p('约束','Constraints'),p('候选架构','Architectures')),step(p('实现','Implementation'),p('同一结构还可有不同 kernel 和存储策略。','The same structure can use different kernels and storage strategies.'),p('架构','Architecture'),p('可运行系统','Runnable system')),step(p('实测','Measure'),p('在同一任务条件下比较结果。','Measure under comparable task conditions.'),p('系统','System'),p('质量与资源报告','Quality/resource report'))],[source.mamba,source.flash],['transformer','rnn','infra']),

  topic('infra','systems',p('AI infra：模型之外的系统','AI infra: the surrounding system'),p('数据、计算、存储、调度和监控一起决定服务能否稳定运行。','Data, compute, storage, scheduling and monitoring determine reliable operation.'),p('GPU：锅我有了。数据管道：米还堵在路上。','The GPU has a pan. The data pipeline is still delivering rice.'),p('像餐厅：厨师之外，还需要采购、排队、出餐与记录。','A restaurant also needs supplies, queues, service and records.'),p('单次模型速度不能代表完整服务；排队、网络与缓存影响用户看到的延迟。','Single-model speed is not whole-service speed. Queues, networks and caches affect latency.'),p('记录请求长度、并发、首 token 延迟、总延迟、吞吐和峰值内存，先定位瓶颈。','Record lengths, concurrency, time to first token, total latency, throughput and peak memory before tuning.'),[
    node(p('数据与存储','Data & storage'),p('可靠供给与版本可追溯。','Reliable input supply and versioning.'),'data-pipeline'),node(p('训练 / 服务','Train / serve'),p('资源分配、批处理与缓存。','Resource allocation, batching and caching.'),'distributed'),node(p('监控','Observe'),p('把质量、延迟和成本一起记录。','Track quality, latency and cost together.'),'results')
  ],[step(p('接入','Ingress'),p('记录请求与完成条件。','Record the request and success conditions.'),p('请求','Request'),p('任务记录','Task record')),step(p('排队','Queue'),p('并发和长度影响等待时间。','Concurrency and lengths affect waiting.'),p('任务','Tasks'),p('可执行批次','Scheduled batch')),step(p('计算','Compute'),p('模型读取权重与 KV，kernel 执行计算。','Kernels compute using weights and KV state.'),p('批次 + 模型','Batch + model'),p('输出','Output')),step(p('观测','Observe'),p('记录端到端指标，避免只优化一小段。','Track end-to-end metrics, not just one segment.'),p('轨迹','Trace'),p('质量 / 延迟 / 内存','Quality / latency / memory'))],[source.vllm,source.tune],['inference','gpu','industry']),

  topic('distributed','systems',p('分布式：人多也要同步','Distributed: coordinate the workers'),p('分割数据、模型或状态，换取规模，同时支付通信成本。','Split data, models or state to scale, while paying communication costs.'),p('四个人写同一份作业，得先说好谁负责哪一页。','Four people sharing an assignment must agree who writes each page.'),p('像合作搬家：分配箱子与路线，还要同步哪部分已完成。','Like a coordinated move: divide boxes and routes, then synchronize progress.'),p('更多设备不保证线性加速；通信、负载不均和故障都可能限制收益。','More devices do not guarantee linear speedup. Communication, imbalance and failures matter.'),p('先测单设备基线，确认有效 batch 与精度，再检查通信和 checkpoint 恢复。','Measure a single-device baseline, match effective batch and precision, then inspect communication and checkpoint recovery.'),[
    node(p('数据并行','Data parallel'),p('模型副本处理不同数据，汇总梯度。','Replicas process different data and combine gradients.'),'optimization'),node(p('模型并行','Model parallel'),p('参数或层分布在不同设备上。','Parameters or layers are distributed across devices.'),'infra'),node(p('状态分片','State sharding'),p('FSDP 分片参数、梯度与优化器状态。','FSDP shards parameters, gradients and optimizer state.'),'industry')
  ],[step(p('划分','Partition'),p('确定按数据、层或参数分割。','Choose data, layer or parameter partitioning.'),p('模型 + 数据','Model + data'),p('设备任务','Worker tasks')),step(p('局部计算','Compute'),p('各设备执行分配的工作。','Workers execute their assigned work.'),p('局部输入','Local input'),p('局部结果','Local results')),step(p('通信','Communicate'),p('收集参数或同步梯度产生通信开销。','Gathering parameters or synchronizing gradients adds communication.'),p('结果 / 状态','Results / state'),p('同步状态','Synchronized state')),step(p('恢复','Recover'),p('checkpoint 必须足以恢复训练。','Checkpoints must support actual recovery.'),p('已同步状态','Synchronized state'),p('可恢复记录','Recoverable record'))],[source.fsdp,source.megatron],['infra','optimization','tuning']),

  topic('gpu','systems',p('显卡生态：不只是一张卡','Accelerator ecosystems'),p('芯片、驱动、编译器、算子、框架与模型支持共同组成生态。','Chips, drivers, compilers, kernels, frameworks and model support form an ecosystem.'),p('插头能插上，不代表所有“祖传代码”都能开饭。','A compatible plug does not guarantee the old code will run.'),p('像厨房设备与食谱：同一目标可能需要不同工具链。','Like kitchen equipment and recipes: a goal may need a different toolchain.'),p('CUDA、ROCm 和 CANN 的覆盖与兼容性随版本变化。这里不做未实测的价格或速度排名。','CUDA, ROCm and CANN support changes with versions. No unmeasured price or speed ranking is presented.'),p('先查目标设备、OS、框架和算子兼容矩阵，再跑最小模型，最后实测自己的负载。','Check device, OS, framework and kernel compatibility; run a minimal model, then measure your workload.'),[
    node(p('NVIDIA / CUDA','NVIDIA / CUDA'),p('CUDA 平台与其工具、库。','CUDA platform, tools and libraries.'),'infra'),node(p('AMD / ROCm','AMD / ROCm'),p('核对受支持设备与框架版本。','Check supported devices and framework versions.'),'industry'),node(p('昇腾 / CANN','Ascend / CANN'),p('使用对应开发工具链与迁移说明。','Use the platform toolchain and migration documentation.'),'quantization')
  ],[step(p('列需求','Requirements'),p('列出模型、精度、算子与部署环境。','List the model, precision, kernels and environment.'),p('任务','Task'),p('需求表','Requirements')),step(p('查兼容','Compatibility'),p('查官方设备与软件支持，而非只看算力数字。','Check official hardware/software support, not only compute figures.'),p('需求表','Requirements'),p('支持配置','Supported setup')),step(p('最小运行','Minimal run'),p('验证模型能执行且结果合理。','Verify execution and plausible results.'),p('配置','Setup'),p('可复现基线','Reproducible baseline')),step(p('实测负载','Benchmark'),p('比较同等质量条件下的端到端指标。','Compare end-to-end metrics at comparable quality.'),p('实际任务','Real workload'),p('测量记录','Measurements'))],[source.cuda,source.rocm,source.ascend,ref('Apple MLX · Framework','https://github.com/ml-explore/mlx')],['infra','quantization','industry']),

  topic('quantization','systems',p('量化：少用几位，多验一次','Quantization: fewer bits, more checks'),p('用有限离散值近似张量，减少存储，但会引入误差。','Approximate tensors with discrete values, reducing storage while introducing error.'),p('行李箱压缩好了，也得看看衬衫有没有被压坏。','Packing tighter still requires checking what got crushed.'),p('像把连续刻度换成有限档位，刻度越少，舍入可能越明显。','Like replacing a continuous dial with a few positions.'),p('位数不直接等于速度；scale、zero-point、校准、异常值与硬件 kernel 都会影响结果。','Bits do not directly determine speed. Scales, zero-points, calibration, outliers and kernels matter.'),p('用任务验证集比较误差、质量、峰值内存和延迟。这里的 uniform toy quantizer 不等同于 GPTQ 或 AWQ。','Compare error, quality, peak memory and latency on task evaluation. This uniform toy quantizer is not GPTQ or AWQ.'),[
    node(p('映射离散值','Map values'),p('按尺度舍入并处理范围。','Scale and round values within a range.'),'vectors'),node(p('误差','Error'),p('恢复近似值后比较原始张量。','Compare dequantized values with the original.'),'results'),node(p('实际收益','Real gains'),p('验证 kernel 支持与端到端指标。','Check kernel support and end-to-end metrics.'),'gpu')
  ],[step(p('原始张量','Tensor'),p('下面使用固定教学数列。','The lab uses fixed teaching values.'),p('浮点数','Floating-point values'),p('范围','Range')),step(p('设尺度','Scale'),p('确定离散刻度与范围。','Choose discrete levels and a range.'),p('范围 + 位数','Range + bits'),p('刻度','Levels')),step(p('舍入','Round'),p('实际计算最近刻度与恢复值。','Calculate nearest levels and reconstructed values.'),p('刻度 + 数值','Levels + values'),p('近似张量','Approximate tensor')),step(p('评估','Evaluate'),p('张量误差与任务质量需要分别检查。','Check tensor error and task quality separately.'),p('近似张量','Approximate tensor'),p('误差 / 质量','Error / quality'))],[source.gptq,source.awq],['gpu','inference','results'],'quantization'),

  topic('ai4s','science',p('AI4S：预测之后，还要验证','AI4S: predictions need validation'),p('AI 可以帮助建模与提出候选，科学结论仍需证据。','AI can model systems and propose candidates; scientific conclusions still need evidence.'),p('AI 不是实验室里的许愿池，投个 prompt 不会自动出论文。','A laboratory is not a wishing well for prompts.'),p('像加速筛选的助手：先减少要检查的候选，再用领域方法验证。','Like a faster screening assistant: narrow candidates, then validate with domain methods.'),p('AlphaFold 3 是生物分子结构与相互作用预测的例子；预测结构不自动证明功能、疗效或机制。','AlphaFold 3 is an example of biomolecular structure and interaction prediction; predicted structure alone does not establish function, efficacy or mechanism.'),p('检查数据分布、置信度、物理或生物约束，并设计独立验证；把模型输出与实验证据分开记录。','Check data distributions, uncertainty and domain constraints; design independent validation and separate predictions from experimental evidence.'),[
    node(p('领域问题','Domain task'),p('定义可检验的问题与约束。','Define a testable question and constraints.'),'data-pipeline'),node(p('模型候选','Candidates'),p('用模型缩小搜索范围。','Use a model to narrow the search.'),'multimodal'),node(p('独立验证','Validation'),p('计算或实验验证模型提出的结果。','Validate proposals computationally or experimentally.'),'results')
  ],[step(p('问题','Question'),p('明确要预测的对象与可验证结果。','Define the object and checkable result.'),p('科学问题','Scientific question'),p('约束与指标','Constraints/metrics')),step(p('数据','Data'),p('检查观测质量与分布。','Check observation quality and distribution.'),p('测量','Measurements'),p('可用数据','Usable data')),step(p('预测','Predict'),p('模型提出候选，并记录不确定性。','Predict candidates and record uncertainty.'),p('输入','Inputs'),p('候选','Candidates')),step(p('验证','Validate'),p('独立证据决定是否接受结论。','Independent evidence determines acceptance.'),p('候选','Candidates'),p('验证结果','Validation result'))],[source.af3],['multimodal','data-pipeline','results']),

  topic('data-pipeline','science',p('数据构建：先修路，再踩油门','Data pipelines: build the road'),p('定义、采集、去重、划分、版本与质量检查构成可复现数据。','Definitions, collection, deduplication, splits, versions and checks support reproducible data.'),p('“大力出奇迹”之前，先看看锅里是不是重复的米。','Before adding more compute, check for duplicated ingredients.'),p('像做饭前择菜：来源、清洗与分装决定后面能否公平比较。','Like preparing ingredients: provenance, cleaning and separation enable fair comparisons.'),p('清洗、特征选择与标准化如果看到了测试集信息，评估可能被污染。','Cleaning, feature selection or scaling can contaminate evaluation if they use test information.'),p('先划分，再在训练集拟合预处理；记录去重规则、时间切分、来源与版本。','Split first and fit preprocessing on training data; record deduplication, time splits, provenance and versions.'),[
    node(p('来源与定义','Provenance'),p('明确样本、标签和可用范围。','Define examples, labels and usable scope.'),'ai4s'),node(p('隔离划分','Split'),p('避免重复与未来信息穿越到测试集。','Keep duplicates and future information out of test data.'),'evals'),node(p('版本与检查','Version & check'),p('同一实验应能找到相同数据。','An experiment should recover the same data.'),'harness')
  ],[step(p('定义','Define'),p('写清楚样本是什么，标签从哪里来。','Define examples and label provenance.'),p('任务','Task'),p('数据定义','Data definition')),step(p('去重 / 划分','Deduplicate / split'),p('按任务选择实体或时间划分。','Choose entity or time splits for the task.'),p('原始样本','Raw examples'),p('独立数据集','Separate sets')),step(p('预处理','Preprocess'),p('只在训练集拟合，再应用到其他集。','Fit on training data, then apply elsewhere.'),p('训练集','Training set'),p('预处理器','Preprocessor')),step(p('存证','Version'),p('记录版本、规则、统计和异常。','Record versions, rules, statistics and anomalies.'),p('成品数据','Prepared data'),p('可复现记录','Reproducible record'))],[source.data,source.rules],['probability','evals','tuning']),

  topic('results','science',p('结果分析：让分母说话','Result analysis: show the denominator'),p('看指标、样本量、误差类型与使用条件，不只看一个漂亮分数。','Inspect metrics, sample size, failure types and conditions, not just one attractive score.'),p('“准确率 100%”——先等等，总共测了几道题？','“100% accuracy”—wait, how many cases were tested?' ),p('像体检：一个数值需要参考范围、测量方式与其他证据。','Like a measurement that needs context, method and supporting observations.'),p('小样本、相关试验与数据偏移会限制结论；交叉验证也不是消除所有偏差的魔法。','Small samples, correlated trials and distribution shifts limit conclusions; cross-validation does not remove every bias.'),p('保留失败样本；按任务类别切片，并在相同数据与资源条件下比较版本。','Retain failures, inspect task slices and compare versions under matching data and resource conditions.'),[
    node(p('指标与分母','Metric & count'),p('明确统计单位与试验数量。','Define the unit and number of trials.'),'evals'),node(p('错误切片','Failure slices'),p('发现在哪类任务中失败。','Identify categories of failures.'),'classification'),node(p('公平比较','Fair comparison'),p('数据、条件与预算都要可追溯。','Track data, conditions and budgets.'),'tuning')
  ],[step(p('收集','Collect'),p('保存每个任务的实际结果。','Save actual results for every task.'),p('任务记录','Task records'),p('结果表','Results table')),step(p('统计','Summarize'),p('同时报告分子、分母与重复条件。','Report successes, denominators and repeat conditions.'),p('结果表','Results'),p('指标','Metrics')),step(p('切片','Slice'),p('按类型和失败机制寻找差异。','Compare categories and failure mechanisms.'),p('指标 + 样本','Metrics + cases'),p('失败模式','Failure patterns')),step(p('决策','Decide'),p('在质量、成本与延迟约束下选择改动。','Choose changes under quality, cost and latency constraints.'),p('对照记录','Comparison records'),p('可检验决策','Checkable decision'))],[source.cv,source.rules],['classification','evals','ai4s']),

  topic('prompting','work',p('提示词：把任务说清楚','Prompting: make the task clear'),p('明确目标、输入、约束、例子与完成条件，比堆形容词更可验证。','Specify the goal, inputs, constraints, examples and success criteria.'),p('“高级感拉满”可以是愿望，但验收还得写人话。','“Make it amazing” is a wish; acceptance criteria need concrete words.'),p('像给同事写任务单：做什么、用什么资料、产出什么、怎样算完成。','Like a brief for a colleague: task, evidence, output and completion criteria.'),p('更长的 prompt 不一定更好；规则冲突、资料不完整和模型限制不会靠语气解决。','A longer prompt is not necessarily better. Tone cannot fix conflicting instructions, missing data or model limits.'),p('用真实样例迭代并固定评估；结构化输出要做格式与内容验证。','Iterate with real cases and fixed evaluation; validate both structure and content.'),[
    node(p('目标与边界','Goal & scope'),p('定义需要做的事与约束。','Define the task and constraints.'),'context'),node(p('资料与示例','Evidence & examples'),p('提供相关输入和目标输出示例。','Provide relevant inputs and examples of desired output.'),'rag'),node(p('验收','Acceptance'),p('用测试或实际状态判断完成。','Use tests or actual state to judge completion.'),'evals')
  ],[step(p('目标','Goal'),p('例：解释卷积并给出可复核计算。','Example: explain convolution with checkable arithmetic.'),p('任务','Task'),p('明确目标','Clear goal')),step(p('输入','Inputs'),p('提供图、核、受众与来源。','Provide the image, kernel, audience and sources.'),p('相关资料','Relevant material'),p('可用上下文','Usable context')),step(p('输出约束','Output contract'),p('规定格式、粒度与缺少资料时的行为。','Specify format, detail and missing-information behavior.'),p('目标 + 输入','Goal + inputs'),p('输出约定','Output contract')),step(p('检查','Check'),p('核对乘加、图文一致性与来源。','Check arithmetic, figure-text consistency and sources.'),p('回答','Answer'),p('通过或修订','Accept or revise'))],[source.prompt],['rag','context','skills']),

  topic('skills','work',p('Skills：可复用的做事方法','Skills: reusable procedures'),p('把任务说明、参考材料和可选脚本包装成可发现的资源。','Package instructions, references and optional scripts as discoverable resources.'),p('菜谱存好了，不代表锅会自己洗。','Saving a recipe does not wash the pan.'),p('像一本按需翻开的操作手册，告诉执行者何时用、怎么做、如何检查。','Like an on-demand manual: when to use it, what to do and how to check the result.'),p('Skill 文件不等于模型新学会的参数，也不自动授予工具权限或保证执行正确。','A Skill file is not a learned model parameter and does not automatically grant permissions or ensure correct execution.'),p('让描述便于发现，正文说明步骤与检查；把长参考放进独立资源，并测试真实触发。','Make descriptions discoverable, document steps and checks, separate long references and test actual invocation.'),[
    node(p('发现','Discover'),p('名称和描述帮助选择合适流程。','Names and descriptions help select procedures.'),'prompting'),node(p('按需读取','Load'),p('正文和参考在需要时读取。','Load instructions and references when needed.'),'context'),node(p('执行与检查','Execute & check'),p('工具由应用运行，结果仍要验证。','The application runs tools and verifies outcomes.'),'harness')
  ],[step(p('匹配任务','Match'),p('判断 Skill 是否适合当前需求。','Check whether the Skill fits the task.'),p('任务 + 描述','Task + description'),p('选择结果','Selection')),step(p('读取说明','Read'),p('读取 SKILL.md 与相关资源。','Read SKILL.md and relevant resources.'),p('资源包','Resource package'),p('操作步骤','Procedure')),step(p('执行','Execute'),p('按授权范围执行工具或脚本。','Execute tools or scripts within authorization.'),p('步骤 + 输入','Procedure + inputs'),p('候选结果','Candidate result')),step(p('验证','Verify'),p('检查实际产物与预期行为。','Check the artifact and expected behavior.'),p('结果','Result'),p('已验证产物','Verified artifact'))],[source.skill],['prompting','context','harness']),

  topic('harness','work',p('Harness：把能力接成系统','Harness: connect the system'),p('组织上下文、工具、执行、检查与恢复，帮助模型持续完成任务。','Organize context, tools, execution, checks and recovery around a model.'),p('接力棒不能只传一句“你接着懂”。','A handoff needs more than “you know what to do.”'),p('像工程脚手架与交班记录，让每一步都有可恢复的状态。','Like scaffolding and a shift log: every step leaves recoverable state.'),p('Harness 不是单一标准化算法；结构随任务变化，也不能让模型永不出错。','Harness is not one standardized algorithm. Structure varies by task and does not remove model errors.'),p('维护任务列表、明确完成条件、记录工具轨迹、保存版本，并检查下一轮能否恢复。','Track tasks, success conditions, tool traces and versions, then test recovery in the next session.'),[
    node(p('状态','State'),p('保存目标、进度和关键资料。','Save goals, progress and relevant evidence.'),'context'),node(p('工具与执行','Tools'),p('执行、错误、结果都有记录。','Record calls, errors and results.'),'agents'),node(p('检查与恢复','Check & resume'),p('实际验证之后再标记完成。','Mark completion only after checking outcomes.'),'evals')
  ],[step(p('初始化','Initialize'),p('建立任务、环境与检查方式。','Set up tasks, environment and checks.'),p('需求','Requirements'),p('可执行状态','Runnable state')),step(p('执行一步','Execute'),p('做一个可检查的改动。','Make one checkable change.'),p('当前状态','Current state'),p('新产物','New artifact')),step(p('验证保存','Check & save'),p('检查结果，留下源码与进度记录。','Verify the result and save source and progress.'),p('产物','Artifact'),p('版本 + 记录','Version + records')),step(p('恢复继续','Resume'),p('下一轮读取状态并选择未完成项。','The next session reads state and selects unfinished work.'),p('记录','Records'),p('下一步','Next step'))],[source.harness],['agents','skills','context']),

  topic('rsi','work',p('RSI：改进也要过考试','RSI: improvements need tests'),p('系统提出自身改动，再用外部可检查的评估决定是否保留。','A system proposes changes to itself and retains them based on checkable evaluation.'),p('自己给自己打满分，这个绩效表就先别信了。','A perfect self-assigned score is not independent evaluation.'),p('像改学习方法：提出新方法，用同一套独立题目比较，而不是只写“我进化了”。','Like revising study methods: compare on independent tasks instead of declaring improvement.'),p('DGM 研究中的代码改进不等于证明无限递归提升；固定 benchmark 进步不保证泛化或改进基础模型权重。','Code improvements in DGM do not prove unbounded recursive improvement. Benchmark gains do not guarantee generalization or changed base-model weights.'),p('保留独立测试、版本和回滚；把提案、测量、接受与部署分成可检查阶段。','Keep independent tests, versions and rollback; separate proposal, measurement, acceptance and deployment.'),[
    node(p('提议','Propose'),p('针对已有失败提出可定位的改动。','Propose targeted changes for observed failures.'),'results'),node(p('独立测试','Test'),p('避免把评估答案直接变成训练或优化目标。','Avoid simply optimizing on evaluation answers.'),'evals'),node(p('保留 / 回滚','Keep / roll back'),p('基于证据保留版本，允许失败候选。','Retain versions on evidence and allow failed candidates.'),'harness')
  ],[step(p('观察失败','Observe'),p('从实际任务找到问题。','Identify a problem from actual tasks.'),p('失败记录','Failure record'),p('改进目标','Improvement target')),step(p('提案','Propose'),p('提出工具、代码或流程改动。','Propose tool, code or procedure changes.'),p('目标','Target'),p('候选版本','Candidate version')),step(p('对照测试','Compare'),p('用保留的独立测试比较。','Compare on retained independent tests.'),p('候选 + 基线','Candidate + baseline'),p('测量结果','Measurements')),step(p('接受 / 回滚','Accept / rollback'),p('只按证据保留；这里仅是流程教学。','Retain based on evidence; this is a teaching flow only.'),p('测量结果','Measurements'),p('可追溯版本','Tracked version'))],[source.rsi],['evals','harness','results']),

  topic('tuning','systems',p('调参：一次只改能解释的东西','Tuning: explain each change'),p('先建可复现基线，区分优化问题、泛化问题与系统瓶颈。','Build a reproducible baseline and distinguish optimization, generalization and system bottlenecks.'),p('学习率、batch、精度一起乱改：这锅到底是谁的？','Change learning rate, batch and precision together—who caused the result?' ),p('像修车先诊断：耗油、发动不起来和轮胎漏气不是同一类问题。','Like diagnosing a car: fuel use, startup failure and a puncture need different fixes.'),p('没有对所有模型通用的最佳参数；大 batch、混合精度或编译优化都有条件。','No setting is best for all models. Large batches, mixed precision and compilation have conditions.'),p('检查学习率与 loss、独立验证集、梯度与数值稳定性；系统优化先 profile，再比较质量和耗时。','Check learning rate, loss, validation, gradients and numerical stability; profile before system optimization and compare quality with time.'),[
    node(p('基线','Baseline'),p('固定数据、版本与测量条件。','Fix data, versions and measurement conditions.'),'data-pipeline'),node(p('诊断','Diagnose'),p('区分 loss、泛化与资源问题。','Separate loss, generalization and resource problems.'),'optimization'),node(p('对照改动','Compare'),p('记录改变与收益，保留失败结果。','Record changes and effects, including failures.'),'results')
  ],[step(p('复现','Reproduce'),p('确认现有结果能重复。','Confirm the baseline can be reproduced.'),p('配置 + 数据','Config + data'),p('基线','Baseline')),step(p('诊断','Diagnose'),p('检查质量和系统测量。','Inspect quality and system measurements.'),p('记录','Records'),p('瓶颈假设','Bottleneck hypothesis')),step(p('单项改动','Change'),p('优先做可以解释的对照。','Prioritize interpretable comparisons.'),p('假设','Hypothesis'),p('候选配置','Candidate config')),step(p('比较','Compare'),p('同等条件下看质量、稳定性与资源。','Compare quality, stability and resources under matching conditions.'),p('对照实验','Comparison'),p('保留或撤回','Retain or revert'))],[source.tune,source.rules],['optimization','distributed','results']),

  topic('industry','systems',p('大厂技术：看它解决哪层问题','Industry tools: locate the layer'),p('架构、训练框架、kernel、服务系统和 Agent 工程各有职责。','Architectures, training frameworks, kernels, serving systems and agent engineering have different roles.'),p('把所有新名词都叫“模型”，就像把整个厨房都叫“锅”。','Calling every new tool a model is like calling a kitchen a pan.'),p('像电脑基础栈：硬件、编译器、库、应用分层理解，版本更新才不容易混淆。','Use a layered computing stack: hardware, compilers, libraries and applications.'),p('厂商文档说明功能，不是跨厂商性能排名；这些例子不构成完整产业目录。','Vendor documentation describes functionality, not a cross-vendor performance ranking. These examples are not an exhaustive industry directory.'),p('NVIDIA Megatron Core 看训练并行，JAX 看变换与编译，DeepSeek 看 MoE/RL，Anthropic 看工具循环与 Harness。再回到自己的任务验证。','Inspect Megatron Core for parallel training, JAX for transformations and compilation, DeepSeek for MoE/RL, and Anthropic for tool loops and harnesses; validate on your own tasks.'),[
    node(p('结构与训练','Model & training'),p('MoE、RL、并行训练处在不同层。','MoE, RL and parallel training occupy different layers.'),'deepseek'),node(p('计算与服务','Compute & serve'),p('编译、kernel 和请求调度不等同于模型参数。','Compilation, kernels and request scheduling are not model parameters.'),'infra'),node(p('工具应用','Tool application'),p('上下文、执行、恢复与评估连接成应用。','Context, execution, recovery and evaluation form an application.'),'harness')
  ],[step(p('找到层次','Locate'),p('先问：改结构、改训练、改计算，还是改应用？','Ask whether it changes structure, training, computation or application.'),p('新名词','New term'),p('所属层','Layer')),step(p('查原始资料','Read source'),p('核对论文或官方文档中的定义与条件。','Check definitions and conditions in primary sources.'),p('层次','Layer'),p('具体机制','Mechanism')),step(p('最小案例','Minimal case'),p('跑一个能够解释结果的例子。','Run an example whose outcome can be explained.'),p('机制','Mechanism'),p('可复现案例','Reproducible case')),step(p('任务验证','Task check'),p('用实际任务测量再决定是否采用。','Measure your task before adopting it.'),p('案例','Case'),p('采用依据','Adoption evidence'))],[source.megatron,source.jax,source.harness,source.r1],['gpu','infra','new-architectures']),
];

export const fieldGroups=[
  {id:'representation',name:p('表示与生成','Representations & generation'),color:'#ff87b4'},
  {id:'systems',name:p('训练与系统','Training & systems'),color:'#ff746b'},
  {id:'science',name:p('科学与数据','Science & data'),color:'#ffcf32'},
  {id:'work',name:p('工作方法','Working methods'),color:'#a2d33e'},
];
