import {lessons,groups,originalSections} from './content.js';
import {englishLessons} from './english.js';
import {fieldGuide,fieldGroups} from './field-guide.js';
const p=(zh,en)=>({zh,en});
const map=(zh,en)=>zh.map((s,i)=>{const [name,detail]=s.split('|'),[ename,edetail]=en[i].split('|');return {name:p(name,ename),detail:p(detail,edetail)};});
const overlay={
intro:{joke:p('GPU 都买了，问题还没想好：这波属于先上车再找路。','Bought the GPU before defining the problem? Find the road before accelerating.'),analogy:p('像用旧账单预测下一次用量：从样本中调整规则。','Like learning from past usage records to predict the next one.'),map:map(['数据|样本给出输入与目标。','模型|用可调整的参数计算预测。','损失|用误差检查当前规则，再更新参数。'],['Data|Examples provide inputs and targets.','Model|Adjustable parameters produce predictions.','Loss|Measure error, then update parameters.'])},
vectors:{joke:p('向量：我有大小，也有方向，不是“随便看看”。','A vector has magnitude and direction. “Somewhere over there” will not do.'),analogy:p('像地图上的位移箭头；矩阵可以同时改变一组箭头。','Like displacement arrows on a map; a matrix transforms them together.'),map:map(['向量|一组有序数值表达对象。','矩阵|线性变换把输入坐标映到新坐标。','基向量|变换后的基向量决定所有线性组合。'],['Vector|Ordered values represent an object.','Matrix|A linear transform maps coordinates.','Basis|Transformed basis vectors determine every linear combination.'])},
calculus:{joke:p('“最近有进步吗？”导数：先看这一小段。','“Am I improving?” The derivative asks about this small interval.'),analogy:p('像速度表看当前变化率；累计里程则对应变化的累积。','A speedometer shows current change; distance accumulates change.'),map:map(['函数|输入变化时，输出怎样变化？','导数|局部变化率是切线斜率。','链式法则|复合步骤的局部导数相乘。'],['Function|How does output change with input?','Derivative|The local rate is the tangent slope.','Chain rule|Multiply local derivatives through composed steps.'])},
probability:{joke:p('“大概吧”也有讲究：概率要算面积，不是看山多高。','“Probably” needs care: probability is an area, not a peak height.'),analogy:p('像一批测量的分布：中心描述位置，宽度描述分散。','Like repeated measurements: the center locates them and width describes spread.'),map:map(['分布|描述可能取值与概率规律。','密度与面积|连续变量的概率来自区间面积。','均值与标准差|改变位置与分散程度。'],['Distribution|Describe possible values and their probabilities.','Density & area|Interval probability is area under a density.','Mean & deviation|Control location and spread.'])},
regression:{joke:p('别急着“拿捏规律”，先看看残差有没有拿捏你。','Before claiming you found the pattern, inspect the residuals.'),analogy:p('像根据过去路程与时间拟合耗时规则；直线只是一个简化模型。','Like fitting a travel-time rule from past journeys; a line is a simplified model.'),map:map(['预测直线|w 和 b 决定每个输入的预测。','残差|真实值与预测值之间的差。','梯度下降|沿降低 MSE 的方向更新参数。'],['Prediction|w and b determine the line.','Residual|The difference between target and prediction.','Gradient descent|Update parameters to reduce MSE.'])},
pytorch:{joke:p('手算梯度：“这题我会。”计算图：“那我们再算一千层。”','“I can differentiate this.” The graph asks for a thousand more layers.'),analogy:p('像记录流水线每一步，反向查每一步对最终变化的贡献。','Record a pipeline, then trace how each step affects the final change.'),map:map(['前向计算|记录算子和中间结果。','局部导数|每个算子有自己的变化规律。','反向传播|把上游梯度按链式法则传回。'],['Forward pass|Record operations and intermediate values.','Local derivative|Each operation has a local rate of change.','Backward pass|Send gradients back through the chain rule.'])},
classification:{joke:p('阈值：我往左一点，误报和漏报就开始吵架。','Move the threshold and false positives argue with false negatives.'),analogy:p('像报警器的灵敏度：更容易响，也可能带来更多误报。','Like alarm sensitivity: more detections may also bring more false alarms.'),map:map(['概率分数|Sigmoid 把线性得分映射到 0–1。','阈值|把分数变成正负决策。','混淆矩阵|分别统计正确、误报与漏报。'],['Score|Sigmoid maps a linear score into 0–1.','Threshold|Turn scores into decisions.','Confusion matrix|Count correct decisions and both error types.'])},
neural:{joke:p('神经网络：名字听着很玄，节点里先把乘加算清楚。','A mysterious name. Inside each node, start with multiply and add.'),analogy:p('像多级调音台：每一层混合输入并改变响应，再交给下一层。','Like stages of a mixing desk: combine inputs, transform the response and pass it on.'),map:map(['加权求和|输入乘权重，再加偏置。','非线性激活|让多层不只是一个线性变换。','输出与训练|输出由计算得到，参数通常从数据学习。'],['Weighted sum|Multiply inputs by weights, then add bias.','Activation|Nonlinearity prevents layers collapsing into one linear transform.','Output & training|Compute output; usually learn parameters from data.'])},
optimization:{joke:p('学习率太大：你以为在冲刺，其实在山谷两边横跳。','A huge learning rate feels fast—until it keeps jumping across the valley.'),analogy:p('像下坡时决定每一步多大；动量会保留过去移动的方向。','Like choosing a downhill step size; momentum retains previous motion.'),map:map(['梯度|指出局部损失的变化方向。','学习率|决定更新步长。','动量|累计历史方向，也可能带来振荡。'],['Gradient|Describe the local direction of loss change.','Learning rate|Control the update size.','Momentum|Accumulate past directions, potentially causing oscillation.'])},
convolution:{joke:p('同一把尺子量全图：卷积主打一个“不换工位”。','One ruler across the image: reuse the same tool at every position.'),analogy:p('像用同一张小模板检查不同位置，比较局部变化。','Use the same small template to inspect local changes across positions.'),map:map(['窗口|只读取当前局部区域。','共享核|所有位置复用同一组权重。','输出格子|逐项乘加，尺寸由核、步幅与 padding 决定。'],['Window|Read the current local region.','Shared kernel|Reuse weights across positions.','Output cell|Multiply and sum; shape depends on kernel, stride and padding.'])},
architectures:{joke:p('Residual：这部分可以改，原件先别扔。','Residual learning: change this part, but keep the original.'),analogy:p('像编辑文档保留原稿，再把修改加上去。','Like retaining a document and adding an edit.'),map:map(['主分支 F(x)|学习输入的变化量。','跳跃路径 x|建立直接的加法路径。','形状匹配|相加之前，两边尺寸要兼容。'],['Branch F(x)|Learn a change to the input.','Skip x|Provide a direct additive path.','Shape match|Addition requires compatible shapes.'])},
nlp:{joke:p('输入法猜中了下一个词，不代表它知道你下班想去哪。','Predicting your next word does not reveal your plans after work.'),analogy:p('像从候选菜单抽选，温度与截断改变抽选分布。','Like drawing from a menu of candidates after changing their probabilities.'),map:map(['Token|文本先变成离散单位。','Logits → Softmax|得分转成候选概率。','采样|Temperature 与 Top-p 改变选择分布。'],['Token|Text becomes discrete units.','Logits → Softmax|Convert scores into probabilities.','Sampling|Temperature and Top-p change the distribution.'])},
rnn:{joke:p('RNN：“这题我记得。”下一步：“记住的是压缩版。”','An RNN remembers a compressed state, not a perfect transcript.'),analogy:p('像一路读书一路更新一张小便签，前面的内容靠状态往后传。','Like reading while updating one small note that carries information forward.'),map:map(['当前输入|每步读取一个新元素。','循环状态|当前输入与上一步状态共同更新。','共享参数|各时间步复用同一组权重。'],['Current input|Read a new element each step.','Recurrent state|Combine input with the previous state.','Shared parameters|Reuse weights across time steps.'])},
translation:{joke:p('“我正在学习”翻译一下：可别全盯着“我”。','Translate “I am learning”—do not stare at only the first word.'),analogy:p('像写译文时回看不同原文片段；每个输出位置读取比例不同。','Like referring to different source passages while writing each target word.'),map:map(['编码|把源序列变成表示。','Cross-attention|目标位置读取源表示的组合。','解码|逐步产生目标 token。'],['Encode|Represent the source sequence.','Cross-attention|Each target position combines source representations.','Decode|Produce target tokens in sequence.'])},
transformer:{joke:p('Attention：重点不是“注意看”，是“按什么权重读”。','Attention asks how much to read from each position.'),analogy:p('像按问题给资料打相关分，再综合内容；打分规则由训练学习。','Score evidence against a question, then combine it; training learns the scoring projections.'),map:map(['Query × Key|点积与缩放产生匹配分数。','Softmax 与 mask|归一化权重，并限制可读位置。','组合 Value|按权重求和得到输出向量。'],['Query × Key|Dot products and scaling create scores.','Softmax & mask|Normalize weights and restrict visibility.','Combine Value|Weighted sums produce an output vector.'])},
pretraining:{joke:p('BERT 可以左右看，GPT 得守住“未来答案别偷看”。','BERT can look both ways; GPT must not peek at future answers.'),analogy:p('像两种练习：补空题可看左右提示，续写只能看已给内容。','Compare filling a gap with continuing a passage from preceding text.'),map:map(['训练目标|Masked token 与 next token 的目标不同。','可见范围|双向和因果遮罩限定读取。','后训练|预训练之后还可塑造任务行为。'],['Objective|Masked-token and next-token targets differ.','Visibility|Bidirectional and causal masks control reading.','Post-training|Later stages can shape task behavior.'])},
llama:{joke:p('位置编码：排队别只说“我也在”，还得说第几位。','A queue needs positions, not just “I am here too.”'),analogy:p('像每个位置把指针转一个角度；两个指针的对比包含相对位置。','Rotate a pointer at each position; comparisons encode relative position.'),map:map(['成对旋转|对向量的二维分量对施加旋转。','相对位置|Q/K 点积包含位置差的影响。','长上下文边界|数学性质不保证任意长度泛化。'],['Pair rotation|Rotate 2D component pairs.','Relative position|Q/K dot products reflect position differences.','Context limits|The property does not guarantee arbitrary-length generalization.'])},
deepseek:{joke:p('MoE 开会：这次叫谁来，不是给谁封“数学总监”。','Routing an expert is not appointing a permanent “math director.”'),analogy:p('像按输入选择少数处理分支，再组合结果；选择规则可学习。','Select a few processing branches for an input, then combine their outputs.'),map:map(['路由|输入得到专家得分。','稀疏选择|每个 token 只激活部分专家。','结果组合|选中输出按权重组合；完整模型还有其他机制。'],['Router|Score experts for the input.','Sparse selection|Activate only some experts per token.','Combine|Weight selected outputs; real models include other mechanisms.'])},
rag:{joke:p('“有出处吗？”RAG：先去翻资料，别现场编参考文献。','“Where is the evidence?” Retrieve it before composing references.'),analogy:p('像开卷考试先找相关页，再基于资料回答。','Like an open-book task: find the relevant page before answering.'),map:map(['检索|从外部资料挑选候选。','上下文|把问题与证据送入这次调用。','核对回答|检索命中不代表答案已被支持。'],['Retrieve|Select candidates from external material.','Context|Provide the question and evidence to the call.','Verify|Retrieval success does not prove answer support.'])},
agents:{joke:p('“我已经做了”——先看工具有没有真的执行。','“Done”—first check whether the tool actually executed.'),analogy:p('像办事时读结果、选下一步、执行、回看是否办成。','Read a result, choose an action, execute it and check completion.'),map:map(['目标与状态|当前任务与已知信息。','工具循环|请求由模型产生，工具由应用执行。','停止条件|按真实结果判断完成。'],['Goal & state|The task and available information.','Tool loop|The model requests; the application executes.','Stop condition|Check completion against actual results.'])},
inference:{joke:p('KV Cache：昨天抄过的笔记，今天别从头再抄。','KV Cache: reuse yesterday’s notes instead of copying them again.'),analogy:p('像保留已算过的中间记录，下一步读取历史并追加新内容。','Retain intermediate records, read them and append new content at the next step.'),map:map(['Prefill|处理已有上下文，建立缓存。','Decode|为新 token 计算并读取历史。','缓存占用|随序列、batch、KV 头数与精度增长。'],['Prefill|Process context and build the cache.','Decode|Compute a new token while reading history.','Storage|Grows with length, batch, KV heads and precision.'])},
lora:{joke:p('微调不一定要全屋装修，先看能不能只加个小改动。','Fine-tuning may need a small addition rather than a complete renovation.'),analogy:p('像在原规则旁加可训练补丁，原有大矩阵保持冻结。','Add a trainable patch while the original large matrix stays frozen.'),map:map(['冻结原权重|不训练基础矩阵 W。','低秩更新 BA|用两个小矩阵表示增量。','Rank 与目标层|决定参数量和更新能力。'],['Freeze W|Keep base weights unchanged.','Low-rank BA|Two small matrices represent the update.','Rank & targets|Control parameter count and capacity.'])},
reasoning:{joke:p('奖励一改，策略：“懂了，原来 KPI 是这个。”','Change the reward and the policy notices a different KPI.'),analogy:p('像根据可检查的结果调整尝试方式，但奖励设计可能偏离真实目标。','Adjust behavior from checkable outcomes; reward design may miss the real goal.'),map:map(['策略|决定不同动作的概率。','奖励|给出优化信号。','验证与训练阶段|区分示例、RL 方法和实际任务能力。'],['Policy|Define action probabilities.','Reward|Provide an optimization signal.','Stages & validation|Distinguish toy updates, RL methods and task capability.'])},
evals:{joke:p('“感觉变强了”先放一边，我们把同一套题再做一遍。','“Feels stronger” can wait. Repeat the same tasks.'),analogy:p('像产品验收：定义结果、重复检查、记录失败，而不只看演示。','Like acceptance testing: define outcomes, repeat checks and retain failures.'),map:map(['完成定义|明确什么结果算成功。','重复与分母|记录试验次数和任务分布。','轨迹与最终状态|同时核对工具、证据和实际结果。'],['Success criteria|Define what counts as success.','Repeats & count|Record trials and task distribution.','Trace & final state|Check tools, evidence and actual outcomes.'])},
};

// The original computation and citations are retained; shorter surfaces are added.
export function getTopics(language='zh'){
  const originals=(language==='en'?englishLessons:lessons).map((l,i)=>{
    const o=overlay[l.id];return {...l,label:l.name,headline:l.summary,joke:o.joke[language],analogy:o.analogy[language],boundary:language==='en'?'This analogy illustrates information flow; use the equations and experiment notes for the precise mathematical definition.':'类比只帮助理解关系；准确计算以公式和实验说明为准。',practice:l.challenge??(language==='en'?'Change one input, inspect the result, then compare it with the calculation.':'改变一个输入，检查结果，再与计算过程对照。'),nodes:o.map.map(n=>({name:n.name[language],detail:n.detail[language]})),group:i<4?'foundations':i<9?'training':i<18?'architecture':'practice',color:i<4?'#369af4':i<9?'#28c5d8':i<18?'#ff9d28':'#43c491',extra:false};
  });
  const ordered=fieldGroups.flatMap(g=>fieldGuide.filter(t=>t.group===g.id));
  const extras=ordered.map((t,i)=>({...t,num:`B${String(i+1).padStart(2,'0')}`,name:t.name[language],label:t.name[language],title:t.name[language],summary:t.summary[language],headline:t.summary[language],joke:t.joke[language],analogy:t.analogy[language],boundary:t.boundary[language],practice:t.practice[language],nodes:t.nodes.map(n=>({...n,name:n.name[language],detail:n.detail[language]})),process:t.process.map(s=>Object.fromEntries(Object.entries(s).map(([k,v])=>[k,v[language]]))),sources:t.sources.map(s=>({...s,date:language==='en'?s.date.replace('文档核对于','Documentation checked on'):s.date})),color:fieldGroups.find(g=>g.id===t.group).color}));
  return [...originals,...extras];
}
export const learningGroups=[
  {id:'foundations',name:p('01 · 数学起点','01 · Foundations'),ids:lessons.slice(0,4).map(l=>l.id),color:'#369af4'},
  {id:'training',name:p('02 · 从数据到模型','02 · Learn to train'),ids:lessons.slice(4,9).map(l=>l.id),color:'#28c5d8'},
  {id:'architecture',name:p('03 · 看懂架构','03 · Architectures'),ids:lessons.slice(9,18).map(l=>l.id),color:'#ff9d28'},
  {id:'practice',name:p('04 · 从模型到应用','04 · Applications'),ids:lessons.slice(18).map(l=>l.id),color:'#43c491'},
  ...fieldGroups.map(g=>({...g,ids:fieldGuide.filter(t=>t.group===g.id).map(t=>t.id)})),
];
export {originalSections};
