import React,{useState} from 'react';
import {Library,ArrowUpRight,ArrowRight,CalendarDays,ChevronRight,LockKeyhole,Download,FileText,Waypoints} from 'lucide-react';
import {models,advances} from './model-atlas.js';
import {selectModelReleases} from './model-history.js';
import {iconFor} from './topic-icons.jsx';
import {publicAsset} from './site-config.js';

const accessLabel=(access,tx)=>access==='both'?tx('API + 权重','API + weights'):access==='weights'?tx('开放权重','Open weights'):access==='report'?tx('研究资料','Research'):tx('托管服务','Hosted');
const AccessIcon=access=>access==='weights'||access==='both'?Download:access==='report'?FileText:LockKeyhole;
const kindLabel=(kind,tx)=>({preview:'Preview',research:tx('研究 / Infra','Research / Infra'),weights:tx('权重公开','Weight release'),checkpoint:'Checkpoint',product:tx('产品 / 工作流','Product / workflow')})[kind];
function ReferenceLinks({sources,tx}){return <div className="release-source">{sources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{/LICENSE|\/terms/.test(s.url)?tx('许可原文','License'):/huggingface/.test(s.url)?tx('模型资料','Model card'):i===0?tx('官方出处','Official source'):tx('补充资料','Reference')}<ArrowUpRight size={11}/></a>)}</div>;}
function Access({release,tx}){const Icon=AccessIcon(release.access);return <div className="release-access"><span><Icon size={11}/>{accessLabel(release.access,tx)}</span><span>{release.license}</span></div>;}
export default function ModelAtlas({language,tx,catalog,Link}){
 const [access,setAccess]=useState('all'),[year,setYear]=useState('2026');
 const list=selectModelReleases(models,{year,access});
 return <article className="model-atlas"><span className="v4-eyebrow">TRY / MODEL FIELD GUIDE · 2026.10.04</span><h1><Library size={28}/>{tx('模型图鉴与技术节点','Models & technical milestones')}</h1><p className="v4-deck">{tx('同一系列，年份、训练方法和开放方式都可能变化。这里按具体发布记录，技术名词可以跳到对应章节。','Dates, training methods and access can change within a family. Browse documented releases and follow technical terms into the course.')}</p>
  <div className="access-guide"><div><strong><LockKeyhole size={17}/>{tx('托管服务','Hosted models')}</strong><p>{tx('像使用云软件，通过产品或 API 调用；通常不能下载模型权重。','Like cloud software: use a product or API; weights are usually unavailable.')}</p></div><div><strong><Download size={17}/>Open weights</strong><p>{tx('下载参数自行运行。许可、训练数据和代码要按具体版本查。','Download parameters to run locally. Check each version’s license, data and code.')}</p></div><div><strong><FileText size={17}/>Open source</strong><p>{tx('还需看可研究、修改和复现的材料及许可；公开报告只是其中一部分。','Also examine materials and licenses for study, modification and reproduction; a report is one part.')}</p></div></div>
  <div className="catalog-filters" role="group" aria-label={tx('筛选模型访问方式','Filter model access')}>{[['all',tx('全部','All')],['hosted',tx('托管服务','Hosted')],['weights',tx('开放权重','Open weights')]].map(([id,label])=><button key={id} aria-pressed={access===id} onClick={()=>setAccess(id)}>{React.createElement(AccessIcon(id==='all'?'report':id),{size:15})}{label}</button>)}</div>
  <div className="model-year-filters" role="group" aria-label={tx('筛选技术节点年份','Filter milestone year')}><span><CalendarDays size={14}/>{tx('年份','Year')}</span>{['2024','2025','2026','all'].map(y=><button key={y} aria-pressed={year===y} onClick={()=>setYear(y)}>{y==='all'?tx('全部年份','All years'):y}</button>)}</div>
  <p className="catalog-count" role="status">{list.length} / 12 {tx('个系列','families')} · {tx('日期与许可对应下方具体发布','Dates and licenses apply to the named releases')}</p>
  <div className="model-list">{list.map(m=>{const releases=m.visibleReleases,latest=releases.at(-1);return <section key={m.id} className="model-row" style={{'--card-color':m.color}}><div className="model-name"><img src={publicAsset('icons/'+m.icon+'.svg')} width="43" height="43" alt=""/><h2>{m.brand}</h2><span>{m.family}</span></div><div className="model-explanation"><div className="model-latest"><div><time dateTime={latest.date}>{latest.date}</time>{latest.datePrecision==='month'&&<small>{tx('月份精度','Month precision')}</small>}{kindLabel(latest.kind,tx)&&<small>{kindLabel(latest.kind,tx)}</small>}</div><h3>{latest.name}</h3><p>{latest.brief[language]}</p><Access release={latest} tx={tx}/><ReferenceLinks sources={latest.sources.slice(0,2)} tx={tx}/></div>
   <div className="model-summary-row"><span><Waypoints size={16}/>{tx('系列技术','Technology')}</span><p>{m.mechanism[language]}</p></div>
   <div className="model-links">{m.links.map(id=><Link key={id} id={id}>{catalog[id].name.split('：')[0].split(':')[0]}<ArrowRight size={12}/></Link>)}</div>
   <details className="model-history" key={year+'-'+access}><summary><CalendarDays size={17}/><strong>{tx('年份与关键节点','Dates & milestones')}</strong><span>{releases.length}</span><ChevronRight size={15}/></summary><div className="release-list">{releases.map(r=><div className="release-item" key={r.name+r.date}><time dateTime={r.date}>{r.date}{r.datePrecision==='month'&&<small>{tx('月份','Month')}</small>}</time><div><h3>{r.name}{kindLabel(r.kind,tx)&&<span>{kindLabel(r.kind,tx)}</span>}</h3><p>{r.brief[language]}</p><Access release={r} tx={tx}/><ReferenceLinks sources={r.sources} tx={tx}/></div></div>)}</div></details>
   <details className="model-boundary"><summary><FileText size={15}/>{tx('版本与资料说明','Release & evidence notes')}<ChevronRight size={14}/></summary><p>{m.boundary[language]}</p></details>
  </div></section>;})}</div>
  {!list.length&&<p className="course-empty">{tx('这个年份没有符合筛选条件的已核实节点。','No verified milestones match these filters.')}</p>}
  <section className="advance-section"><h2><Waypoints size={21}/>{tx('技术改变了什么','What the techniques change')}</h2><p>{tx('这几条路径可以贯穿不同模型系列。点进章节，先看计算过程，再看使用条件。','These paths connect model families. Follow a chapter to see the computation and its practical conditions.')}</p><div className="advance-grid">{advances.map((a,i)=>{const Icon=iconFor({id:a.link});return <div key={a.title} style={{'--advance-color':a.color}}><h3><span><Icon size={17}/></span>{a.title}</h3><p>{a.text[language]}</p><div><a href={'#'+a.link}>{tx('对应章节','Related chapter')}<ArrowRight size={13}/></a><a href={a.source.url} target="_blank" rel="noreferrer">{tx('原始资料','Primary reference')}<ArrowUpRight size={12}/></a></div></div>;})}</div></section>
  <p className="source-snapshot">{tx('核对日期：2026-10-04。保留模型、权重、论文和产品节点的区别。缺少日级证据时只写月份；内部架构以公开材料为准。','Checked October 4, 2026. Model, weight, paper and product dates are distinguished. Month precision is retained where day-level evidence is missing; internals follow public disclosures.')}</p>
 </article>;
}
