const p=(zh,en)=>({zh,en});
const ref=(title,url)=>({title,url});
export {models} from './model-history.js';
export const advances=[
 {title:'Transformer / Pretraining',color:'#369af4',text:p('先通过大规模 token 预测学习表示。Attention 让位置之间能按输入计算读取权重，预训练目标决定模型怎样利用上下文。','Learn representations through large-scale token prediction. Attention computes how positions read one another; the objective controls how context is used.'),link:'pretraining',source:ref('Attention Is All You Need','https://arxiv.org/abs/1706.03762')},
 {title:'Data × Compute',color:'#28c5d8',text:p('Chinchilla 研究给定训练算力下参数与 token 的平衡。实际方案还要看数据质量、去重、推理成本；不是参数越多越适合。','Chinchilla studies the parameter–token balance under a training compute budget. Real decisions also need data quality, deduplication and inference cost.'),link:'data-pipeline',source:ref('Training Compute-Optimal LLMs','https://arxiv.org/abs/2203.15556')},
 {title:'SFT / Preference / RL',color:'#43c491',text:p('SFT 学习示范，偏好训练倾向更合适的回答，RL 用奖励调整策略。它们改变行为，仍需检查事实和任务结果。','SFT learns demonstrations, preference training favors desired answers and RL adjusts a policy from rewards. Behavior changes still require factual and task checks.'),link:'alignment',source:ref('InstructGPT','https://arxiv.org/abs/2203.02155')},
 {title:'Reasoning Budget',color:'#ffcf32',text:p('推理时可给模型更多计算、采样或检验机会。更长的 CoT 可能有用，也可能浪费；应比较成功率、延迟和费用。','More inference compute can fund reasoning, sampling or verification. Longer CoT may help or waste resources; compare success, latency and cost.'),link:'cot',source:ref('DeepSeek-R1','https://arxiv.org/abs/2501.12948')},
 {title:'MoE / MLA / GQA',color:'#ff9d28',text:p('MoE 减少每次激活的专家；MLA 压缩注意力缓存；GQA 共享 K/V 头。不同机制改善不同瓶颈，总参数仍可能占很多内存。','MoE reduces active experts, MLA compresses attention caches and GQA shares K/V heads. They target different bottlenecks; total weights can still require substantial memory.'),link:'deepseek',source:ref('DeepSeek-V3','https://arxiv.org/abs/2412.19437')},
 {title:'Flash / Paged / Quantization',color:'#ff746b',text:p('FlashAttention 优化读写与计算组织，PagedAttention 管理缓存，量化缩减数值存储。它们不是同一种新架构，速度要在目标硬件上测。','FlashAttention reorganizes I/O and computation, PagedAttention manages caches and quantization reduces storage precision. They are not one architecture; measure speed on target hardware.'),link:'infra',source:ref('FlashAttention','https://arxiv.org/abs/2205.14135')},
 {title:'Multimodal',color:'#ff87b4',text:p('图像、音频等先变成模型可用的表示，再与文本协作。能描述图像不代表具有物理世界的全部知识，输入输出模态也可能不同。','Images and audio become representations usable with text. Describing an image does not establish complete physical understanding, and input and output modalities can differ.'),link:'multimodal',source:ref('Gemma 3 Technical Report','https://arxiv.org/abs/2503.19786')},
 {title:'Tools / Harness / Evals',color:'#a2d33e',text:p('把模型接入工具、环境、状态、权限和检查，才能处理连续任务。系统质量往往取决于恢复和验收；演示成功不能代表稳定可用。','Tools, environments, state, permissions and checks support sustained tasks. Recovery and acceptance matter; a successful demo does not establish reliability.'),link:'harness',source:ref('Effective harnesses for long-running agents','https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents')},
];
