import React,{useState,useEffect,useRef} from 'react';
import {PenLine,Plus,X,Trash2,RotateCcw,Download,Upload,Check,ArrowUpRight,Search} from 'lucide-react';
import {NOTE_KEY,tagColors,createNote,parseNotebook,notebookRecord,mergeNotes} from './notes.js';

export function useNotebook(){
 const initial=useRef(null);if(!initial.current){try{const raw=localStorage.getItem(NOTE_KEY);initial.current={notes:raw?parseNotebook(raw):[],status:'saved',raw};}catch{initial.current={notes:[],status:'load-error',raw:null};}}
 const [notes,setNotes]=useState(initial.current.notes),[status,setStatus]=useState(initial.current.status),blocked=useRef(initial.current.status==='load-error');
 useEffect(()=>{if(blocked.current)return;try{localStorage.setItem(NOTE_KEY,JSON.stringify(notebookRecord(notes)));setStatus('saved');}catch{setStatus('save-error');}},[notes]);
 const commit=next=>{if(JSON.stringify(notebookRecord(next)).length>2000000){setStatus('capacity');return false;}setNotes(next);return true;};
 const update=(id,patch)=>commit(notes.map(n=>n.id===id?{...n,...patch,updatedAt:new Date().toISOString()}:n));
 const add=topicId=>{if(blocked.current||notes.length>=1000)return null;const n=createNote(topicId);return commit([n,...notes])?n.id:null;};
 const restoreBackup=value=>{const incoming=parseNotebook(value);const merged=mergeNotes(notes,incoming);if(!commit(merged))throw new Error('NOTEBOOK_CAPACITY');blocked.current=false;return incoming.length;};
 return {notes,status,update,add,restoreBackup};
}

export default function Notebook({notebook,topicId='',catalog,tx,language,inline=false,open=false,onClose}){
 const {notes,status,update,add,restoreBackup}=notebook;
 const [query,setQuery]=useState(''),[trash,setTrash]=useState(false),[selected,setSelected]=useState(null),[filter,setFilter]=useState(''),[tag,setTag]=useState(''),[color,setColor]=useState('blue');
 const [backupMode,setBackupMode]=useState(null),[backup,setBackup]=useState(''),[error,setError]=useState(''),[feedback,setFeedback]=useState('');
 const dialog=useRef(null),backupDialog=useRef(null),backupText=useRef(null),fileInput=useRef(null),titleRef=useRef(null);
 useEffect(()=>{if(!inline){if(open)dialog.current?.showModal();else dialog.current?.close();}},[open,inline]);
 useEffect(()=>{setSelected(null);setQuery('');setFilter('');setTrash(false);},[topicId,open]);
 useEffect(()=>{if(backupMode){backupDialog.current?.showModal();backupText.current?.focus();if(backupMode==='export')backupText.current?.select();}else backupDialog.current?.close();},[backupMode]);
 const active=notes.find(n=>n.id===selected),scope=inline?'':topicId;
 const list=notes.filter(n=>Boolean(n.deletedAt)===trash&&(!scope||n.topicId===scope)&&(!filter||n.tags.some(t=>t.label===filter))&&`${n.title} ${n.body} ${n.tags.map(t=>t.label).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));
 const labels=[...new Set(notes.filter(n=>!n.deletedAt&&(!scope||n.topicId===scope)).flatMap(n=>n.tags.map(t=>t.label)))];
 const saveFile=()=>{const u=URL.createObjectURL(new Blob([backup],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='try-notebook-v5.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500);};
 const apply=value=>{try{const count=restoreBackup(value);setFeedback(tx(`已合并 ${count} 条笔记；同一条记录保留较新的修改。`,`Merged ${count} notes; newer edits win.`));setBackupMode(null);setSelected(null);}catch{setError(tx('备份格式不正确或超出容量；现有笔记未改变。','Invalid or oversized backup. Existing notes are unchanged.'));}};
 const addTag=(label=tag,chosen=color)=>{label=label.trim().slice(0,24);if(!active||!label||active.tags.length>=12||active.tags.some(t=>t.label===label))return;update(active.id,{tags:[...active.tags,{label,color:chosen}]});setTag('');};
 const newNote=()=>{const id=add(topicId);if(id){setSelected(id);setTrash(false);setFilter('');setQuery('');}else setFeedback(tx('无法新增：请检查保存提示或备份容量。','Unable to add a note. Check the storage message or capacity.'));};
 const content=<><div className="notebook-head"><div><span className="v4-eyebrow">NOTEBOOK</span><h1><PenLine size={24}/>{scope?tx('这一章的笔记','Chapter notes'):tx('我的笔记','My notebook')}</h1></div>{!inline&&<button className="v4-icon" aria-label={tx('关闭笔记','Close notebook')} onClick={onClose}><X size={21}/></button>}</div>
 <p className="notebook-intro">{scope?catalog[scope]?.name:tx('按章节记下自己的解释、问题和实践。','Keep your explanations, questions and experiments by chapter.')} <span>{tx('保存在此浏览器；换设备可导出备份。','Saved in this browser; export to move devices.')}</span></p>
 <div className="notebook-toolbar"><button className="v4-primary" onClick={newNote}><Plus size={16}/>{tx('新笔记','New note')}</button><button className="v4-quiet" onClick={()=>{setBackup(JSON.stringify(notebookRecord(notes),null,2));setBackupMode('export');setError('');}}><Download size={15}/>{tx('备份','Backup')}</button><button className="v4-quiet" onClick={()=>{setBackup('');setBackupMode('import');setError('');}}><Upload size={15}/>{tx('导入','Import')}</button><button className={`v4-quiet ${trash?'is-selected':''}`} aria-pressed={trash} onClick={()=>{setTrash(!trash);setSelected(null);}}><Trash2 size={15}/>{trash?tx('回到笔记','Back to notes'):tx('回收站','Trash')}</button><span className={`note-save-status ${status==='saved'?'':'storage-error'}`} role="status">{status==='saved'?<><Check size={13}/>{tx('已保存到本机','Saved locally')}</>:status==='load-error'?tx('原记录无法读取，已保留。请导入备份恢复。','Stored notes could not be read and are preserved. Import a backup.'):status==='capacity'?tx('笔记容量达到上限，本次修改未保存；请缩短内容。','Notebook capacity reached; this edit was not saved. Shorten the content.'):tx('本机保存失败，请立即备份当前笔记。','Local save failed. Back up the current notes.')}</span></div>
 {feedback&&<p className="notebook-feedback" role="status">{feedback}</p>}
 <div className="notebook-search"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label={tx('搜索笔记','Search notes')} placeholder={tx('搜索笔记、问题或标签…','Search notes, questions or tags…')}/></label><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label={tx('筛选笔记标签','Filter note tags')}><option value="">{tx('全部标签','All tags')}</option>{labels.map(t=><option key={t}>{t}</option>)}</select></div>
 <div className={`notebook-workspace ${active?'editing':''}`}><div className="note-list">{list.length?list.map(n=><button key={n.id} className={`note-card ${selected===n.id?'selected':''}`} onClick={()=>setSelected(n.id)}><div><span className="note-emoji">{n.emoji}</span><strong>{n.title||tx('未命名笔记','Untitled note')}</strong></div><p>{n.body.slice(0,110)||tx('写下一个问题，或者用自己的话解释。','Write a question or explain it in your own words.')}</p><div className="note-tags">{n.tags.map(t=><span key={t.label} style={{'--tag-color':tagColors[t.color]}}>{t.label}</span>)}</div><small>{catalog[n.topicId]?.name.split('：')[0].split(':')[0]||tx('未归类','Unassigned')} · {new Date(n.updatedAt).toLocaleDateString(language==='en'?'en-GB':'zh-CN')}</small></button>):<div className="note-empty"><PenLine size={27}/><p>{trash?tx('回收站是空的。','The trash is empty.'):query||filter?tx('没有符合条件的笔记。','No matching notes.'):tx('还没有笔记。可以先记下一个没弄懂的地方。','No notes yet. Start with something you want to understand.')}</p></div>}</div>
 {active&&<div className="note-editor" key={active.id}><div className="note-editor-head"><strong>{active.deletedAt?tx('已回收，可恢复','In trash · recoverable'):tx('编辑笔记','Edit note')}</strong><button className="v4-icon" aria-label={tx('关闭编辑','Close editor')} onClick={()=>setSelected(null)}><X size={17}/></button></div>{active.deletedAt?<><h2>{active.emoji} {active.title||tx('未命名笔记','Untitled note')}</h2><p className="note-body-preview">{active.body}</p><button className="v4-primary" onClick={()=>{update(active.id,{deletedAt:null});setSelected(null);setTrash(false);}}><RotateCcw size={15}/>{tx('恢复笔记','Restore note')}</button></>:<>
 <label>{tx('标题','Title')}<input ref={titleRef} maxLength={100} value={active.title} onChange={e=>update(active.id,{title:e.target.value})} aria-label={tx('笔记标题','Note title')} placeholder={tx('比如：为什么 Q 和 K 要分开？','e.g. Why are Q and K separate?')}/></label>
 <label>{tx('笔记','Note')}<textarea maxLength={20000} value={active.body} onChange={e=>update(active.id,{body:e.target.value})} aria-label={tx('笔记正文','Note body')} placeholder={tx('用自己的话解释；也可以记问题、代码或实验结果。','Explain it in your words, or record questions, code and results.')}/></label>
 <div className="emoji-picks" role="group" aria-label={tx('选择表情','Choose emoji')}>{['📝','🌈','💡','🧠','🤔','🚀','🐱','🍉'].map(e=><button key={e} aria-label={e} aria-pressed={active.emoji===e} onClick={()=>update(active.id,{emoji:e})}>{e}</button>)}<input value={active.emoji} maxLength={64} onChange={e=>update(active.id,{emoji:e.target.value})} aria-label={tx('自定义表情','Custom emoji')}/></div>
 <div className="note-tags editable">{active.tags.map(t=><button key={t.label} style={{'--tag-color':tagColors[t.color]}} onClick={()=>update(active.id,{tags:active.tags.filter(x=>x.label!==t.label)})} aria-label={tx(`移除标签 ${t.label}`,`Remove tag ${t.label}`)}>{t.label}<X size={12}/></button>)}</div>
 <div className="tag-presets">{[[tx('概念','Concept'),'blue'],[tx('疑问','Question'),'yellow'],[tx('实践','Practice'),'green'],[tx('回顾','Review'),'pink']].map(([l,c])=><button key={c} onClick={()=>addTag(l,c)} style={{'--tag-color':tagColors[c]}}>+ {l}</button>)}</div>
 <div className="tag-add"><input value={tag} maxLength={24} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addTag();}}} aria-label={tx('自定义标签','Custom tag')} placeholder={tx('自定义标签','Custom tag')}/><button className="v4-icon" disabled={!tag.trim()} aria-label={tx('添加标签','Add tag')} onClick={()=>addTag()}><Plus size={18}/></button></div><div className="color-picks" role="group" aria-label={tx('标签颜色','Tag color')}>{Object.entries(tagColors).map(([c,b])=><button key={c} style={{background:b}} aria-label={c} aria-pressed={color===c} onClick={()=>setColor(c)}>{color===c&&<Check size={14}/>}</button>)}</div>
 <div className="note-editor-bottom">{catalog[active.topicId]&&<a href={`#${active.topicId}`} onClick={!inline?onClose:undefined}>{tx('回到章节','Open chapter')}<ArrowUpRight size={14}/></a>}<button className="v4-quiet" onClick={()=>{update(active.id,{deletedAt:new Date().toISOString()});setSelected(null);}}><Trash2 size={14}/>{tx('移到回收站','Move to trash')}</button></div>
 </>}</div>}</div></>;
 const backupUI=<dialog ref={backupDialog} className="progress-import-dialog" onClose={()=>setBackupMode(null)} aria-labelledby="notebook-backup-title"><div className="progress-import-head"><h2 id="notebook-backup-title">{backupMode==='export'?tx('保存笔记备份','Back up notes'):tx('导入笔记备份','Import notes')}</h2><button aria-label={tx('关闭笔记备份','Close note backup')} onClick={()=>setBackupMode(null)}><X size={20}/></button></div><p>{backupMode==='export'?tx('包含所有笔记、标签、表情和回收站记录。保存文件，或复制以下内容。','Includes all notes, tags, emoji and trash. Save a file or copy the text.'):tx('导入会与现有记录合并，同一条笔记保留较新的修改。','Import merges with existing notes, keeping newer edits of the same note.')}</p><input hidden ref={fileInput} type="file" accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];if(f){try{if(f.size>2000000)throw new Error();apply(await f.text());}catch{setError(tx('无法读取文件或文件太大；现有笔记未改变。','Unreadable or oversized file. Existing notes unchanged.'));}}e.target.value='';}}/>{backupMode==='import'&&<button className="v4-quiet" onClick={()=>fileInput.current?.click()}>{tx('选择文件','Choose file')}</button>}<label>{tx('笔记备份内容','Note backup contents')}<textarea ref={backupText} readOnly={backupMode==='export'} value={backup} onChange={e=>setBackup(e.target.value)} aria-label={tx('笔记备份内容','Note backup contents')}/></label>{error&&<p role="alert" className="import-error">{error}</p>}<div className="progress-import-actions">{backupMode==='export'?<><button className="v4-quiet" onClick={saveFile}>{tx('保存文件','Save file')}</button><button className="v4-primary" onClick={async()=>{try{await navigator.clipboard.writeText(backup);setFeedback(tx('备份已复制。','Backup copied.'));}catch{backupText.current?.focus();backupText.current?.select();setFeedback(tx('已选中备份，请手动复制。','Backup selected. Copy it manually.'));}}}>{tx('复制备份','Copy backup')}</button></>:<button className="v4-primary" disabled={!backup.trim()} onClick={()=>apply(backup)}>{tx('合并这份备份','Merge this backup')}</button>}</div></dialog>;
 return inline?<article className="notebook-page">{content}{backupUI}</article>:<><dialog ref={dialog} className="notebook-dialog" onClose={onClose} aria-label={tx('章节笔记','Chapter notebook')}>{content}</dialog>{backupUI}</>;
}
